from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    {'category_id': 'crypto_trading', 'title': 'DeFi Yield Farming Guide', 'description': 'Navigate DeFi yield opportunities safely', 'content': 'Create a guide for yield farming in [PROTOCOL]. Include risk assessment, APY calculation, impermanent loss protection, and exit strategy.', 'is_premium': 0, 'difficulty': 'Expert', 'estimated_time': '20 min', 'tags': ['defi', 'yield farming', 'crypto']},
    {'category_id': 'nft_creation', 'title': 'NFT Collection Roadmap', 'description': 'Plan successful NFT launches', 'content': 'Create an NFT collection roadmap for [PROJECT]. Include art style, utility, minting strategy, community building, and post-launch plans.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '20 min', 'tags': ['nft', 'roadmap', 'launch']},
    {'category_id': 'nft_creation', 'title': 'NFT Marketing Strategy', 'description': 'Promote NFT collections effectively', 'content': 'Design a marketing strategy for [NFT PROJECT]. Include Discord growth, Twitter engagement, influencer partnerships, and whitelist tactics.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['nft', 'marketing', 'community']},
    {'category_id': 'voice_cloning', 'title': 'Voice Clone Business Model', 'description': 'Monetize voice cloning technology', 'content': 'Create a business model using voice cloning for [USE CASE]. Include target market, pricing, legal considerations, and scaling strategy.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['voice', 'ai', 'business']},
    {'category_id': 'ai_automation', 'title': 'Workflow Automation Blueprint', 'description': 'Automate repetitive business tasks', 'content': 'Design an automation workflow for [PROCESS] using [TOOLS]. Include triggers, actions, error handling, and ROI calculation.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['automation', 'workflow', 'efficiency']},
    {'category_id': 'ai_automation', 'title': 'Chatbot Conversation Designer', 'description': 'Create engaging chatbot flows', 'content': 'Design a chatbot conversation flow for [PURPOSE]. Include greeting, intent recognition, response variations, and fallback handling.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['chatbot', 'ai', 'conversation']},
    {'category_id': 'virtual_reality', 'title': 'VR Experience Storyboard', 'description': 'Plan immersive VR experiences', 'content': 'Create a VR experience storyboard for [CONCEPT]. Include user journey, interaction points, environment design, and engagement mechanics.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '20 min', 'tags': ['vr', 'experience', 'design']},
    {'category_id': 'marketing_sales', 'title': 'Referral Program Designer', 'description': 'Build viral referral systems', 'content': 'Design a referral program for [PRODUCT]. Include incentive structure, sharing mechanics, tracking system, and viral loop optimization.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['referral', 'growth', 'viral']},
    {'category_id': 'marketing_sales', 'title': 'Retargeting Campaign Strategy', 'description': 'Convert abandoned visitors into customers', 'content': 'Create a retargeting campaign for [PRODUCT]. Include audience segments, ad creatives, messaging sequence, and conversion optimization.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['retargeting', 'ads', 'conversion']},
    {'category_id': 'marketing_sales', 'title': 'Influencer Outreach Template', 'description': 'Partner with influencers effectively', 'content': 'Write an influencer outreach message for [BRAND/PRODUCT]. Include personalization, value proposition, collaboration ideas, and terms.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '8 min', 'tags': ['influencer', 'outreach', 'partnerships']},
    {'category_id': 'writing', 'title': 'Storytelling Framework', 'description': 'Craft compelling brand stories', 'content': 'Create a brand story for [COMPANY] using the hero\'s journey framework. Include origin, challenge, transformation, and mission.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['storytelling', 'branding', 'narrative']},
    {'category_id': 'writing', 'title': 'Headline Formula Generator', 'description': 'Write attention-grabbing headlines', 'content': 'Generate 20 headline variations for [TOPIC] using proven formulas. Include curiosity, benefit, urgency, and specificity-driven headlines.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['headlines', 'copywriting', 'attention']},
    {'category_id': 'content_creation', 'title': 'Content Repurposing Strategy', 'description': 'Maximize content ROI across platforms', 'content': 'Create a repurposing strategy for [CONTENT TYPE]. Transform it into 10+ formats for different platforms while maintaining core message.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['repurposing', 'efficiency', 'multi-platform']},
    {'category_id': 'content_creation', 'title': 'Live Stream Planning Guide', 'description': 'Plan engaging live stream sessions', 'content': 'Plan a live stream for [TOPIC]. Include pre-stream promotion, content outline, engagement tactics, technical setup, and post-stream strategy.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['live stream', 'engagement', 'planning']},
    {'category_id': 'freelancing', 'title': 'Value-Based Pricing Calculator', 'description': 'Price services based on value delivered', 'content': 'Calculate value-based pricing for [SERVICE]. Assess client ROI, market rates, your expertise, and create tiered pricing options.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['pricing', 'value', 'freelancing']},
    {'category_id': 'freelancing', 'title': 'Project Timeline Estimator', 'description': 'Estimate project timelines accurately', 'content': 'Create a project timeline for [PROJECT TYPE]. Break down tasks, estimate hours, add buffer time, and identify dependencies.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['timeline', 'planning', 'estimation']},
    {'category_id': 'business_strategy', 'title': 'Pivot Strategy Framework', 'description': 'Navigate business pivots successfully', 'content': 'Design a pivot strategy for [BUSINESS] moving from [OLD] to [NEW]. Include validation, transition plan, and risk mitigation.', 'is_premium': 0, 'difficulty': 'Expert', 'estimated_time': '20 min', 'tags': ['pivot', 'strategy', 'transformation']},
    {'category_id': 'business_strategy', 'title': 'OKR Goal Setting System', 'description': 'Set and track objectives effectively', 'content': 'Create OKRs for [TEAM/COMPANY] for [TIMEFRAME]. Include objectives, key results, initiatives, and measurement framework.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['okr', 'goals', 'management']},
    {'category_id': 'social_media', 'title': 'Community Management Playbook', 'description': 'Build engaged online communities', 'content': 'Create a community management playbook for [PLATFORM]. Include engagement tactics, moderation guidelines, and growth strategies.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['community', 'engagement', 'management']},
    {'category_id': 'social_media', 'title': 'Social Media Crisis Response', 'description': 'Handle social media crises professionally', 'content': 'Create a crisis response plan for [SCENARIO]. Include immediate actions, communication templates, escalation process, and recovery strategy.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['crisis', 'reputation', 'management']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Done!")
