from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    {'category_id': 'marketing_sales', 'title': 'Cold Email Outreach Sequence', 'description': 'Create personalized cold email campaigns', 'content': 'Write a 5-email cold outreach sequence for [PRODUCT/SERVICE] targeting [ROLE] at [COMPANY TYPE]. Include personalization tactics, value propositions, and follow-up timing.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['email', 'outreach', 'b2b']},
    {'category_id': 'marketing_sales', 'title': 'Facebook Ad Copy Generator', 'description': 'Write high-converting Facebook ad copy', 'content': 'Create 5 Facebook ad variations for [PRODUCT] targeting [AUDIENCE]. Include attention-grabbing hooks, benefit-focused body copy, and compelling CTAs.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['facebook ads', 'advertising', 'copywriting']},
    {'category_id': 'marketing_sales', 'title': 'SEO Content Brief Creator', 'description': 'Generate detailed SEO content briefs', 'content': 'Create an SEO content brief for [KEYWORD]. Include search intent, target word count, H2/H3 structure, LSI keywords, competitor analysis, and content angle.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['seo', 'content', 'strategy']},
    {'category_id': 'writing', 'title': 'Newsletter Hook Generator', 'description': 'Write engaging newsletter openings', 'content': 'Generate 10 attention-grabbing newsletter hooks for [TOPIC]. Make them curiosity-driven, benefit-focused, and encourage readers to keep reading.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['newsletter', 'hooks', 'engagement']},
    {'category_id': 'writing', 'title': 'LinkedIn Article Writer', 'description': 'Create thought leadership LinkedIn articles', 'content': 'Write a LinkedIn article about [TOPIC] that positions you as an expert. Include personal story, actionable insights, data points, and engagement-driving conclusion.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['linkedin', 'thought leadership', 'content']},
    {'category_id': 'content_creation', 'title': 'Podcast Episode Outline', 'description': 'Structure engaging podcast episodes', 'content': 'Create a detailed podcast episode outline for [TOPIC]. Include intro hook, main segments, talking points, guest questions, and outro CTA.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['podcast', 'planning', 'content']},
    {'category_id': 'content_creation', 'title': 'Viral Tweet Thread Creator', 'description': 'Write engaging Twitter threads', 'content': 'Create a viral Twitter thread about [TOPIC]. Start with a hook tweet, include 8-12 value-packed tweets, use storytelling, and end with a CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['twitter', 'threads', 'viral']},
    {'category_id': 'content_creation', 'title': 'Video Script Template', 'description': 'Write engaging video scripts', 'content': 'Write a video script for [TOPIC] that keeps viewers engaged. Include pattern interrupt intro, value delivery, storytelling elements, and strong CTA.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['video', 'script', 'youtube']},
    {'category_id': 'freelancing', 'title': 'Rate Increase Email', 'description': 'Professionally raise your freelance rates', 'content': 'Write an email to existing client announcing rate increase from [OLD RATE] to [NEW RATE]. Justify value, maintain relationship, and handle objections.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '10 min', 'tags': ['rates', 'negotiation', 'clients']},
    {'category_id': 'freelancing', 'title': 'Portfolio Project Descriptions', 'description': 'Write compelling portfolio case studies', 'content': 'Write a portfolio case study for [PROJECT]. Include client challenge, your solution, process, results with metrics, and testimonial integration.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['portfolio', 'case study', 'showcase']},
    {'category_id': 'business_strategy', 'title': 'Pricing Strategy Framework', 'description': 'Develop optimal pricing for your product', 'content': 'Create a pricing strategy for [PRODUCT/SERVICE]. Analyze value-based pricing, competitor pricing, psychological pricing tactics, and tiered pricing options.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['pricing', 'strategy', 'revenue']},
    {'category_id': 'business_strategy', 'title': 'Customer Avatar Builder', 'description': 'Define your ideal customer profile', 'content': 'Create a detailed customer avatar for [BUSINESS]. Include demographics, psychographics, pain points, goals, objections, and buying triggers.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['customer', 'avatar', 'targeting']},
    {'category_id': 'social_media', 'title': 'Instagram Caption Formula', 'description': 'Write engaging Instagram captions', 'content': 'Create 15 Instagram captions for [NICHE] using proven formulas. Include hooks, storytelling, value, and CTAs that drive engagement and saves.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '10 min', 'tags': ['instagram', 'captions', 'engagement']},
    {'category_id': 'social_media', 'title': 'TikTok Content Calendar', 'description': 'Plan 30 days of TikTok content', 'content': 'Create a 30-day TikTok content calendar for [NICHE]. Include trending sounds, content pillars, posting times, and viral content ideas.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['tiktok', 'planning', 'content calendar']},
    {'category_id': 'social_media', 'title': 'Pinterest Pin Description Writer', 'description': 'Optimize Pinterest pins for discovery', 'content': 'Write SEO-optimized Pinterest pin descriptions for [TOPIC]. Include keywords, compelling copy, and CTAs that drive clicks to your website.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['pinterest', 'seo', 'traffic']},
    {'category_id': 'productivity', 'title': 'Morning Routine Optimizer', 'description': 'Design a high-performance morning routine', 'content': 'Create a personalized morning routine for [GOAL/PROFESSION]. Include wake time, activities, time blocks, and habits that maximize energy and focus.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['routine', 'habits', 'productivity']},
    {'category_id': 'productivity', 'title': 'Meeting Agenda Template', 'description': 'Run efficient and productive meetings', 'content': 'Create a meeting agenda template for [MEETING TYPE]. Include objectives, time allocations, discussion points, decision framework, and action items.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['meetings', 'efficiency', 'management']},
    {'category_id': 'development_tech', 'title': 'Code Review Checklist', 'description': 'Comprehensive code review guidelines', 'content': 'Create a code review checklist for [LANGUAGE/FRAMEWORK]. Include code quality, security, performance, testing, and documentation standards.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '10 min', 'tags': ['code review', 'quality', 'development']},
    {'category_id': 'development_tech', 'title': 'Git Commit Message Generator', 'description': 'Write clear and consistent commit messages', 'content': 'Generate professional git commit messages for [CHANGES]. Follow conventional commits format with type, scope, description, and breaking changes.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '3 min', 'tags': ['git', 'version control', 'documentation']},
    {'category_id': 'learning_education', 'title': 'Spaced Repetition Study Plan', 'description': 'Optimize learning with spaced repetition', 'content': 'Create a spaced repetition study schedule for [SUBJECT]. Include review intervals, active recall techniques, and progress tracking system.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['studying', 'memory', 'learning']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Done!")
