from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    {'category_id': 'money_making', 'title': 'Digital Product Idea Generator', 'description': 'Find profitable digital product ideas', 'content': 'Generate 10 digital product ideas for [NICHE] based on market gaps, audience pain points, and monetization potential. Include pricing and launch strategy.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['digital products', 'ideas', 'monetization']},
    {'category_id': 'money_making', 'title': 'Affiliate Marketing Funnel', 'description': 'Build high-converting affiliate funnels', 'content': 'Design an affiliate marketing funnel for [PRODUCT]. Include lead magnet, email sequence, content strategy, and conversion optimization tactics.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['affiliate', 'funnel', 'conversion']},
    {'category_id': 'money_making', 'title': 'Online Course Outline Creator', 'description': 'Structure profitable online courses', 'content': 'Create a complete course outline for [TOPIC]. Include modules, lessons, learning objectives, assignments, and pricing tiers.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['courses', 'education', 'monetization']},
    {'category_id': 'money_making', 'title': 'Membership Site Blueprint', 'description': 'Launch a recurring revenue membership', 'content': 'Design a membership site for [NICHE]. Include content pillars, pricing tiers, retention strategies, and community engagement tactics.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '20 min', 'tags': ['membership', 'recurring revenue', 'community']},
    {'category_id': 'writing', 'title': 'Press Release Writer', 'description': 'Write newsworthy press releases', 'content': 'Write a press release for [ANNOUNCEMENT]. Include attention-grabbing headline, newsworthy angle, quotes, boilerplate, and media contact info.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['pr', 'media', 'announcement']},
    {'category_id': 'writing', 'title': 'Product Description Optimizer', 'description': 'Write converting product descriptions', 'content': 'Write a compelling product description for [PRODUCT]. Focus on benefits over features, use sensory language, address objections, and include SEO keywords.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['ecommerce', 'copywriting', 'conversion']},
    {'category_id': 'writing', 'title': 'Case Study Writer', 'description': 'Create persuasive case studies', 'content': 'Write a case study showcasing [RESULT] for [CLIENT]. Use problem-solution-results format with specific metrics and compelling narrative.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['case study', 'proof', 'storytelling']},
    {'category_id': 'content_creation', 'title': 'Webinar Script Generator', 'description': 'Create engaging webinar presentations', 'content': 'Write a webinar script for [TOPIC] that converts attendees. Include hook, value delivery, storytelling, Q&A handling, and pitch sequence.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '20 min', 'tags': ['webinar', 'presentation', 'sales']},
    {'category_id': 'content_creation', 'title': 'Infographic Content Planner', 'description': 'Plan data-driven infographics', 'content': 'Create an infographic content plan for [TOPIC]. Include data points, visual hierarchy, color scheme, and shareability elements.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['infographic', 'visual', 'data']},
    {'category_id': 'content_creation', 'title': 'Carousel Post Creator', 'description': 'Design educational carousel posts', 'content': 'Create a 10-slide carousel post about [TOPIC] for Instagram/LinkedIn. Include hook slide, value slides, and CTA slide with engaging copy.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '10 min', 'tags': ['carousel', 'social media', 'education']},
    {'category_id': 'freelancing', 'title': 'Scope Creep Prevention System', 'description': 'Protect your time and boundaries', 'content': 'Create a system to prevent scope creep for [SERVICE]. Include contract clauses, communication templates, and change request process.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '12 min', 'tags': ['boundaries', 'contracts', 'management']},
    {'category_id': 'freelancing', 'title': 'Client Onboarding Checklist', 'description': 'Streamline new client onboarding', 'content': 'Create a client onboarding checklist for [SERVICE]. Include welcome email, questionnaire, contract, payment setup, and kickoff meeting agenda.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['onboarding', 'process', 'clients']},
    {'category_id': 'freelancing', 'title': 'Testimonial Request Template', 'description': 'Get powerful client testimonials', 'content': 'Write a testimonial request email for [PROJECT TYPE]. Include specific questions that elicit detailed, results-focused testimonials.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['testimonials', 'social proof', 'clients']},
    {'category_id': 'business_strategy', 'title': 'Market Entry Strategy', 'description': 'Enter new markets successfully', 'content': 'Develop a market entry strategy for [PRODUCT] in [MARKET]. Include competitive analysis, positioning, go-to-market plan, and success metrics.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '20 min', 'tags': ['strategy', 'market', 'expansion']},
    {'category_id': 'business_strategy', 'title': 'Brand Voice Guidelines', 'description': 'Define consistent brand communication', 'content': 'Create brand voice guidelines for [BRAND]. Include personality traits, tone examples, dos and donts, and messaging pillars.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['branding', 'voice', 'communication']},
    {'category_id': 'business_strategy', 'title': 'Partnership Proposal Template', 'description': 'Pitch win-win business partnerships', 'content': 'Write a partnership proposal for [COMPANY] to collaborate on [OPPORTUNITY]. Include mutual benefits, terms, and success metrics.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['partnerships', 'collaboration', 'growth']},
    {'category_id': 'social_media', 'title': 'YouTube Video Title Optimizer', 'description': 'Write click-worthy YouTube titles', 'content': 'Generate 10 YouTube title variations for [VIDEO TOPIC]. Use curiosity gaps, power words, and SEO keywords to maximize CTR.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['youtube', 'titles', 'ctr']},
    {'category_id': 'social_media', 'title': 'LinkedIn Engagement Strategy', 'description': 'Grow your LinkedIn presence', 'content': 'Create a 30-day LinkedIn engagement strategy for [GOAL]. Include posting schedule, content types, commenting strategy, and networking tactics.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['linkedin', 'networking', 'growth']},
    {'category_id': 'social_media', 'title': 'Hashtag Research Strategy', 'description': 'Find high-performing hashtags', 'content': 'Research and categorize hashtags for [NICHE]. Include high-volume, medium, and niche hashtags with engagement potential analysis.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['hashtags', 'reach', 'discovery']},
    {'category_id': 'productivity', 'title': 'Email Management System', 'description': 'Achieve inbox zero efficiently', 'content': 'Create an email management system for [ROLE]. Include filtering rules, response templates, batching schedule, and unsubscribe strategy.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['email', 'organization', 'efficiency']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Done!")
