from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    {'category_id': 'productivity', 'title': 'Focus Session Planner', 'description': 'Maximize deep work sessions', 'content': 'Design a focus session plan for [TASK]. Include preparation, environment setup, distraction blocking, break schedule, and energy management.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['focus', 'deep work', 'concentration']},
    {'category_id': 'productivity', 'title': 'Delegation Framework', 'description': 'Delegate tasks effectively', 'content': 'Create a delegation framework for [TEAM/VA]. Include task selection criteria, instruction templates, quality standards, and feedback system.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '12 min', 'tags': ['delegation', 'management', 'scaling']},
    {'category_id': 'development_tech', 'title': 'Bug Report Template', 'description': 'Write clear and actionable bug reports', 'content': 'Create a bug report for [ISSUE]. Include steps to reproduce, expected vs actual behavior, environment details, and screenshots.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['bugs', 'testing', 'documentation']},
    {'category_id': 'development_tech', 'title': 'Technical Documentation Writer', 'description': 'Create developer-friendly documentation', 'content': 'Write technical documentation for [FEATURE/API]. Include overview, setup instructions, code examples, troubleshooting, and FAQs.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['documentation', 'technical writing', 'development']},
    {'category_id': 'development_tech', 'title': 'Database Schema Designer', 'description': 'Design efficient database structures', 'content': 'Design a database schema for [APPLICATION]. Include tables, relationships, indexes, constraints, and optimization considerations.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '20 min', 'tags': ['database', 'schema', 'architecture']},
    {'category_id': 'learning_education', 'title': 'Feynman Technique Explainer', 'description': 'Learn by teaching concepts simply', 'content': 'Explain [COMPLEX TOPIC] using the Feynman Technique. Break it down into simple terms, use analogies, and identify knowledge gaps.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['learning', 'understanding', 'teaching']},
    {'category_id': 'learning_education', 'title': 'Exam Strategy Planner', 'description': 'Prepare strategically for exams', 'content': 'Create an exam preparation strategy for [SUBJECT] with [X] days remaining. Include topic prioritization, practice schedule, and revision tactics.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['exams', 'strategy', 'preparation']},
    {'category_id': 'learning_education', 'title': 'Mind Map Creator', 'description': 'Visualize concepts with mind maps', 'content': 'Create a mind map structure for [TOPIC]. Include main branches, sub-topics, connections, and key concepts for visual learning.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['mind map', 'visual learning', 'organization']},
    {'category_id': 'psychology', 'title': 'Cognitive Bias Identifier', 'description': 'Recognize and overcome cognitive biases', 'content': 'Identify cognitive biases affecting [DECISION/SITUATION]. Explain each bias, its impact, and strategies to overcome it.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '12 min', 'tags': ['psychology', 'decision making', 'biases']},
    {'category_id': 'psychology', 'title': 'Habit Formation Blueprint', 'description': 'Build lasting habits scientifically', 'content': 'Design a habit formation plan for [HABIT]. Use habit stacking, implementation intentions, and environmental design based on behavioral science.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['habits', 'behavior', 'psychology']},
    {'category_id': 'psychology', 'title': 'Emotional Intelligence Scenarios', 'description': 'Practice EQ in difficult situations', 'content': 'Create EQ practice scenarios for [SITUATION TYPE]. Include emotional awareness, empathy responses, and conflict resolution strategies.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '12 min', 'tags': ['emotional intelligence', 'communication', 'relationships']},
    {'category_id': 'fitness_health', 'title': 'Workout Plan Generator', 'description': 'Create personalized workout routines', 'content': 'Design a [X]-week workout plan for [GOAL] with [EQUIPMENT]. Include exercises, sets, reps, progression, and recovery days.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['fitness', 'workout', 'training']},
    {'category_id': 'fitness_health', 'title': 'Meal Prep Strategy', 'description': 'Plan efficient weekly meal prep', 'content': 'Create a meal prep plan for [DIET TYPE] and [GOAL]. Include shopping list, prep schedule, recipes, and storage instructions.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '12 min', 'tags': ['nutrition', 'meal prep', 'health']},
    {'category_id': 'fitness_health', 'title': 'Sleep Optimization Protocol', 'description': 'Improve sleep quality scientifically', 'content': 'Create a sleep optimization protocol for [SLEEP ISSUE]. Include sleep hygiene, environment setup, routine, and tracking methods.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['sleep', 'recovery', 'health']},
    {'category_id': 'ai_art', 'title': 'Midjourney Style Guide', 'description': 'Master consistent AI art styles', 'content': 'Create a Midjourney style guide for [ART STYLE]. Include prompt formulas, parameters, artist references, and consistency techniques.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['midjourney', 'ai art', 'prompts']},
    {'category_id': 'ai_art', 'title': 'AI Art Business Ideas', 'description': 'Monetize AI-generated artwork', 'content': 'Generate 10 business ideas using AI art for [NICHE]. Include monetization methods, target market, and competitive advantages.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['ai art', 'business', 'monetization']},
    {'category_id': 'research_analysis', 'title': 'Competitive Intelligence Report', 'description': 'Analyze competitors systematically', 'content': 'Create a competitive intelligence report for [COMPETITOR]. Include product analysis, pricing, marketing tactics, strengths, and opportunities.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '20 min', 'tags': ['research', 'competition', 'analysis']},
    {'category_id': 'research_analysis', 'title': 'Survey Question Designer', 'description': 'Create effective research surveys', 'content': 'Design a survey to research [TOPIC]. Include question types, avoid bias, ensure clarity, and structure for actionable insights.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '12 min', 'tags': ['survey', 'research', 'data']},
    {'category_id': 'research_analysis', 'title': 'Trend Analysis Framework', 'description': 'Identify and analyze market trends', 'content': 'Analyze trends in [INDUSTRY/NICHE]. Identify emerging patterns, predict future developments, and recommend strategic actions.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['trends', 'forecasting', 'strategy']},
    {'category_id': 'crypto_trading', 'title': 'Crypto Portfolio Strategy', 'description': 'Build balanced crypto portfolios', 'content': 'Design a crypto portfolio strategy for [RISK LEVEL] with [AMOUNT]. Include allocation, diversification, rebalancing, and risk management.', 'is_premium': 0, 'difficulty': 'Advanced', 'estimated_time': '15 min', 'tags': ['crypto', 'portfolio', 'investing']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Done!")
