from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    # Free Prompts
    {'category_id': 'marketing_sales', 'title': 'Email Subject Line Generator', 'description': 'Write high-open-rate email subject lines', 'content': 'Generate 20 email subject line variations for [TOPIC/OFFER]. Include: curiosity-driven, benefit-focused, urgency-based, and personalized angles. Test for mobile preview length and spam trigger words.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['email', 'subject lines', 'open rates']},
    {'category_id': 'content_creation', 'title': 'Instagram Reel Hooks Generator', 'description': 'Create scroll-stopping reel openings', 'content': 'Generate 20 Instagram reel hooks for [NICHE]. Include pattern interrupts, bold statements, questions, and curiosity gaps that stop scrolling in first 3 seconds.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['instagram', 'reels', 'hooks']},
    {'category_id': 'writing', 'title': 'Blog Post Outline Generator', 'description': 'Structure SEO-optimized blog posts', 'content': 'Create detailed blog post outline for [KEYWORD]. Include: SEO title, meta description, H2/H3 structure, key points for each section, internal linking opportunities, and FAQ section.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['blogging', 'seo', 'content']},
    {'category_id': 'social_media', 'title': 'Viral Video Ideas Generator', 'description': 'Generate trending video concepts', 'content': 'Generate 20 viral video ideas for [NICHE] on [PLATFORM]. Include: hook, content angle, trending audio suggestions, and engagement tactics.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['video', 'viral', 'ideas']},
    {'category_id': 'freelancing', 'title': 'Client Objection Handler', 'description': 'Overcome common client objections', 'content': 'Create responses to common objections for [SERVICE]: "Too expensive", "Need to think about it", "Can I get a discount", "What if it doesn\'t work". Include empathy, reframe, and close techniques.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['sales', 'objections', 'clients']},
    {'category_id': 'business_strategy', 'title': 'SWOT Analysis Generator', 'description': 'Analyze business strengths and weaknesses', 'content': 'Perform SWOT analysis for [BUSINESS/IDEA]. Identify: Strengths (internal advantages), Weaknesses (internal limitations), Opportunities (external factors), Threats (external risks). Include strategic recommendations.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['strategy', 'analysis', 'planning']},
    {'category_id': 'productivity', 'title': 'Daily Task Prioritizer', 'description': 'Prioritize tasks using proven frameworks', 'content': 'Prioritize [TASKS] using Eisenhower Matrix (urgent/important). Categorize into: Do First, Schedule, Delegate, Eliminate. Include time estimates and energy levels.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['productivity', 'prioritization', 'time management']},
    {'category_id': 'development_tech', 'title': 'Code Documentation Generator', 'description': 'Write clear code documentation', 'content': 'Generate documentation for [CODE/FUNCTION]. Include: purpose, parameters, return values, usage examples, edge cases, and error handling.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['documentation', 'code', 'development']},
    {'category_id': 'learning_education', 'title': 'Study Schedule Creator', 'description': 'Plan effective study sessions', 'content': 'Create study schedule for [SUBJECT/EXAM] with [X] days available. Include: topic breakdown, time allocation, active recall sessions, practice tests, and review days.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '10 min', 'tags': ['studying', 'planning', 'schedule']},
    {'category_id': 'money_making', 'title': 'Side Hustle Idea Generator', 'description': 'Find profitable side hustle ideas', 'content': 'Generate 10 side hustle ideas for someone with [SKILLS/INTERESTS] and [AVAILABLE TIME]. Include: startup cost, time investment, income potential, and first steps.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['side hustle', 'ideas', 'income']},
    
    # Premium Prompts
    {'category_id': 'money_making', 'title': 'E-Commerce Brand Builder - $1M+ Strategy', 'description': 'Build 7-figure DTC brand from scratch', 'content': 'Build DTC e-commerce brand in [NICHE] to $1M+ revenue. Include: product selection (winning criteria), supplier sourcing, brand identity development, Shopify store optimization, product photography, email marketing automation (welcome, abandoned cart, post-purchase), SMS marketing, influencer seeding strategy, paid ads (Meta, Google, TikTok), retention tactics, subscription model, customer lifetime value optimization, and scaling roadmap. Include financial projections, tech stack, and 12-month timeline.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['ecommerce', 'dtc', 'brand building']},
    
    {'category_id': 'marketing_sales', 'title': 'Attribution & Analytics Mastery', 'description': 'Track and optimize marketing ROI', 'content': 'Build complete attribution system for [BUSINESS]. Include: pixel setup (Meta, Google, TikTok), Google Analytics 4 configuration, conversion tracking, attribution modeling (first-click, last-click, linear, time-decay), customer journey mapping, cohort analysis, LTV calculation, CAC optimization, ROAS tracking, dashboard creation, and data-driven decision framework. Implement proper tracking for accurate scaling.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['analytics', 'attribution', 'tracking']},
    
    {'category_id': 'content_creation', 'title': 'Documentary Storytelling Framework', 'description': 'Master documentary narrative structure', 'content': 'Create documentary storytelling framework for [SUBJECT]. Include: three-act structure, character development, conflict escalation, emotional beats, interview techniques, B-roll strategy, narrative voiceover, music selection, pacing, and resolution. Study techniques from: Ken Burns, Errol Morris, Werner Herzog. Include shot list and interview questions.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['documentary', 'storytelling', 'filmmaking']},
    
    {'category_id': 'freelancing', 'title': 'Niche Domination Strategy', 'description': 'Become the go-to expert in your niche', 'content': 'Dominate [NICHE] as the recognized expert. Include: micro-niche selection, competitive analysis, unique positioning, signature methodology creation, content domination strategy, SEO for service pages, case study development, speaking opportunities, podcast tour, book/guide creation, community building, strategic partnerships, and pricing premium. Become the only choice for premium clients.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['niche', 'positioning', 'authority']},
    
    {'category_id': 'business_strategy', 'title': 'Venture Capital Fundraising Playbook', 'description': 'Raise VC funding for your startup', 'content': 'Raise [AMOUNT] in VC funding for [STARTUP]. Include: pitch deck creation (problem, solution, market, traction, team, financials), investor targeting, email outreach templates, pitch refinement, due diligence preparation, term sheet negotiation, cap table management, investor updates, and post-money strategy. Cover pre-seed to Series A. Include pitch deck template and financial model.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['fundraising', 'vc', 'startup']},
    
    {'category_id': 'writing', 'title': 'Screenplay & Script Development', 'description': 'Write professional film/TV scripts', 'content': 'Write [GENRE] screenplay/script for [CONCEPT]. Include: logline development, three-act structure, character development, dialogue techniques, scene construction, conflict escalation, subplot integration, theme development, formatting standards, and revision process. Cover feature films, TV pilots, and short films. Include script template and industry standards.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['screenplay', 'scriptwriting', 'film']},
    
    {'category_id': 'social_media', 'title': 'Influencer Brand Building System', 'description': 'Build personal brand that attracts deals', 'content': 'Build influencer brand in [NICHE] that attracts $10K+ brand deals. Include: niche selection, content pillars, posting strategy, engagement tactics, media kit creation, rate card development, brand outreach templates, negotiation tactics, contract essentials, content deliverables, FTC compliance, talent management, and scaling to multiple platforms. Include sponsorship tracker and rate calculator.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['influencer', 'brand deals', 'monetization']},
    
    {'category_id': 'development_tech', 'title': 'Blockchain & Web3 Development', 'description': 'Build decentralized applications', 'content': 'Develop [DAPP/WEB3 PROJECT] on [BLOCKCHAIN]. Include: smart contract development (Solidity/Rust), wallet integration, token economics, NFT functionality, DeFi protocols, gas optimization, security auditing, frontend integration (Web3.js/Ethers.js), IPFS storage, testing framework, deployment strategy, and user onboarding. Include code examples and architecture diagrams.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['blockchain', 'web3', 'smart contracts']},
    
    {'category_id': 'psychology', 'title': 'Consumer Psychology & Neuromarketing', 'description': 'Apply psychology to marketing', 'content': 'Apply consumer psychology to [PRODUCT/SERVICE]. Include: cognitive biases (anchoring, scarcity, social proof), neuromarketing principles, color psychology, pricing psychology, decision-making triggers, emotional drivers, persuasion techniques, FOMO tactics, loss aversion, reciprocity principle, and behavioral economics. Create psychological framework for maximum conversion.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['psychology', 'neuromarketing', 'persuasion']},
    
    {'category_id': 'research_analysis', 'title': 'Data Science & Predictive Analytics', 'description': 'Extract insights from complex data', 'content': 'Perform data analysis for [BUSINESS PROBLEM] using [DATA]. Include: data cleaning, exploratory analysis, statistical testing, predictive modeling, machine learning algorithms, feature engineering, model validation, visualization, insights extraction, and actionable recommendations. Use Python/R for analysis. Include code examples and interpretation guide.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['data science', 'analytics', 'machine learning']},
    
]

init_database()
print(f"Adding {len(PROMPTS)} prompts (mixed free & premium)...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Final batch complete!")
