from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

# Add 20+ more prompts to reach 500+
PROMPTS = [
    # Free Prompts (10)
    {'category_id': 'marketing_sales', 'title': 'Ad Copy Generator', 'description': 'Write converting ads', 'content': 'Create ad copy for [PRODUCT]. Include: headline, body, CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['ads', 'copy', 'marketing']},
    {'category_id': 'content_creation', 'title': 'Video Hook Ideas', 'description': 'Create attention-grabbing hooks', 'content': 'Generate 20 video hooks for [TOPIC]. Include: questions, statements, curiosity.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['video', 'hooks', 'attention']},
    {'category_id': 'writing', 'title': 'Email Newsletter Template', 'description': 'Write engaging newsletters', 'content': 'Create newsletter for [TOPIC]. Include: subject, intro, content, CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['newsletter', 'email', 'content']},
    {'category_id': 'social_media', 'title': 'Story Ideas Generator', 'description': 'Create engaging stories', 'content': 'Generate 20 story ideas for [NICHE]. Include: polls, questions, behind-scenes.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['stories', 'engagement', 'social']},
    {'category_id': 'freelancing', 'title': 'Invoice Template', 'description': 'Professional invoicing', 'content': 'Create invoice for [SERVICE]. Include: header, items, terms, payment.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['invoice', 'billing', 'business']},
    {'category_id': 'business_strategy', 'title': 'SWOT Analysis', 'description': 'Analyze business position', 'content': 'Conduct SWOT for [BUSINESS]. Include: strengths, weaknesses, opportunities, threats.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['swot', 'analysis', 'strategy']},
    {'category_id': 'productivity', 'title': 'Daily Planner', 'description': 'Plan productive days', 'content': 'Plan day for [GOALS]. Include: priorities, schedule, breaks, review.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['planning', 'daily', 'productivity']},
    {'category_id': 'development_tech', 'title': 'Code Comments Generator', 'description': 'Document code properly', 'content': 'Generate comments for [CODE]. Include: purpose, parameters, examples.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['code', 'documentation', 'comments']},
    {'category_id': 'learning_education', 'title': 'Study Notes Template', 'description': 'Take effective notes', 'content': 'Create notes for [TOPIC]. Include: key points, examples, questions, summary.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['notes', 'study', 'learning']},
    {'category_id': 'money_making', 'title': 'Side Hustle Validator', 'description': 'Validate business ideas', 'content': 'Validate [IDEA]. Include: market, competition, costs, revenue, feasibility.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['validation', 'side hustle', 'business']},
    
    # Premium Prompts (10)
    {'category_id': 'money_making', 'title': 'Multiple Revenue Streams System', 'description': 'Build diversified income', 'content': 'Build revenue streams in [NICHE]. Include: passive income, active income, products, services, affiliate, sponsorships, scaling to $100K+/month. Create diversified income system.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['revenue', 'diversification', 'scaling']},
    {'category_id': 'marketing_sales', 'title': 'Marketing Automation Framework', 'description': 'Automate marketing processes', 'content': 'Build marketing automation for [BUSINESS]. Include: email sequences, lead scoring, segmentation, CRM integration, analytics, optimization. Automate 80% of marketing tasks.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['automation', 'marketing', 'efficiency']},
    {'category_id': 'content_creation', 'title': 'Content Empire System', 'description': 'Build content business', 'content': 'Build content business in [NICHE]. Include: strategy, production, distribution, monetization, team, tools, analytics, scaling to $50K+/month. Create content empire.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['content', 'business', 'scaling']},
    {'category_id': 'freelancing', 'title': 'Service Scaling Framework', 'description': 'Scale service business', 'content': 'Scale service business to $100K+. Include: positioning, packaging, pricing, team, operations, systems, client success, scaling. Create scalable service business.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['scaling', 'services', 'systems']},
    {'category_id': 'business_strategy', 'title': 'Strategic Planning System', 'description': 'Create winning strategy', 'content': 'Develop strategic plan for [BUSINESS]. Include: vision, mission, goals, strategy, execution, tracking. Create comprehensive strategic plan.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['strategy', 'planning', 'execution']},
    {'category_id': 'writing', 'title': 'Copywriting Mastery Framework', 'description': 'Master persuasive copywriting', 'content': 'Master copywriting for [PURPOSE]. Include: research, psychology, headlines, storytelling, benefits, objections, CTAs, testing, optimization. Create converting copy.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['copywriting', 'persuasion', 'conversion']},
    {'category_id': 'social_media', 'title': 'Social Media Empire System', 'description': 'Build social media business', 'content': 'Build social media business in [NICHE]. Include: growth, content, monetization, brand deals, products, services, community, scaling to $50K+/month. Create social media empire.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['social media', 'business', 'monetization']},
    {'category_id': 'development_tech', 'title': 'Tech Startup Framework', 'description': 'Build successful startup', 'content': 'Build tech startup from idea to scale. Include: validation, MVP, tech stack, team, funding, launch, growth, scaling. Create successful tech startup.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['startup', 'tech', 'scaling']},
    {'category_id': 'psychology', 'title': 'Behavioral Psychology Framework', 'description': 'Apply psychology to business', 'content': 'Apply behavioral psychology to [BUSINESS]. Include: cognitive biases, decision-making, motivation, habits, persuasion, behavior change. Use psychology to grow business.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['psychology', 'behavior', 'persuasion']},
    {'category_id': 'research_analysis', 'title': 'Market Research Framework', 'description': 'Conduct professional research', 'content': 'Conduct market research for [BUSINESS]. Include: market size, customer segments, competition, opportunities, threats, strategic recommendations. Create comprehensive research report.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['research', 'market', 'analysis']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts to reach 500+...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ 500+ REACHED!")
