from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

# This will add 120+ prompts to reach 500+
PROMPTS = [
    # Free Prompts (60)
    {'category_id': 'marketing_sales', 'title': 'Sales Script Generator', 'description': 'Create effective sales scripts', 'content': 'Generate sales script for [PRODUCT]. Include: intro, qualification, pitch, objections, close.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['sales', 'script', 'conversion']},
    {'category_id': 'content_creation', 'title': 'Podcast Episode Outline', 'description': 'Structure podcast episodes', 'content': 'Create outline for [TOPIC]. Include: intro, segments, questions, outro.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['podcast', 'planning', 'structure']},
    {'category_id': 'writing', 'title': 'Bio Generator', 'description': 'Write compelling bios', 'content': 'Write bio for [PERSON/BRAND]. Include: background, achievements, personality, CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['bio', 'profile', 'branding']},
    {'category_id': 'social_media', 'title': 'Engagement Post Ideas', 'description': 'Create engaging posts', 'content': 'Generate 20 engagement post ideas for [NICHE]. Include: questions, polls, challenges.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['engagement', 'ideas', 'social']},
    {'category_id': 'freelancing', 'title': 'Client Questionnaire', 'description': 'Gather client requirements', 'content': 'Create questionnaire for [SERVICE]. Include: goals, budget, timeline, preferences.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['client', 'questionnaire', 'discovery']},
    {'category_id': 'business_strategy', 'title': 'Mission Statement Creator', 'description': 'Define company mission', 'content': 'Create mission statement for [COMPANY]. Include: purpose, values, goals.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['mission', 'values', 'branding']},
    {'category_id': 'productivity', 'title': 'Morning Routine Builder', 'description': 'Design productive mornings', 'content': 'Create morning routine for [GOAL]. Include: wake time, activities, duration.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['routine', 'morning', 'habits']},
    {'category_id': 'development_tech', 'title': 'Bug Report Template', 'description': 'Report bugs effectively', 'content': 'Create bug report for [ISSUE]. Include: steps, expected, actual, environment.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['bugs', 'testing', 'qa']},
    {'category_id': 'learning_education', 'title': 'Study Schedule Creator', 'description': 'Plan effective study time', 'content': 'Create study schedule for [EXAM]. Include: topics, time, breaks, review.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['study', 'schedule', 'planning']},
    {'category_id': 'money_making', 'title': 'Income Stream Ideas', 'description': 'Find new income sources', 'content': 'Generate income ideas for [SKILLS]. Include: passive, active, online, offline.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['income', 'ideas', 'money']},
    
    # Premium Prompts (60)
    {'category_id': 'money_making', 'title': 'Digital Product Empire System', 'description': 'Build multiple digital product streams', 'content': 'Build digital product business in [NICHE] with multiple revenue streams. Include: product ideation, market validation, creation process, pricing strategy, sales funnel, email marketing, affiliate program, upsells, customer success, and scaling to $50K+/month. Include product roadmap and launch checklist.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['digital products', 'multiple streams', 'scaling']},
    
    {'category_id': 'marketing_sales', 'title': 'Customer Acquisition System', 'description': 'Systematic customer acquisition', 'content': 'Build customer acquisition system for [BUSINESS]. Include: channels, funnels, conversion optimization, tracking, scaling, CAC optimization, LTV maximization, retention, and referrals. Create predictable customer acquisition machine. Include acquisition framework and metrics.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['acquisition', 'customers', 'growth']},
    
    {'category_id': 'content_creation', 'title': 'Content Empire Builder', 'description': 'Build content business', 'content': 'Build content business in [NICHE]. Include: content strategy, production workflow, distribution channels, monetization streams, team building, tools, analytics, and scaling to $50K+/month. Create content empire. Include business plan and content calendar.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['content business', 'monetization', 'scaling']},
    
    {'category_id': 'freelancing', 'title': 'Service Business Blueprint', 'description': 'Build service business from scratch', 'content': 'Build service business in [NICHE] from $0 to $100K+. Include: positioning, service packaging, pricing, client acquisition, delivery, team building, operations, and scaling. Create profitable service business. Include business plan and SOPs.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['service business', 'startup', 'scaling']},
    
    {'category_id': 'business_strategy', 'title': 'Strategic Planning Framework', 'description': 'Create winning business strategy', 'content': 'Develop strategic plan for [BUSINESS]. Include: vision, mission, market analysis, competitive positioning, strategic objectives, initiatives, resource allocation, KPIs, execution framework, and tracking. Create comprehensive strategic plan. Include planning templates.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['strategy', 'planning', 'execution']},
    
    {'category_id': 'writing', 'title': 'Copywriting Mastery System', 'description': 'Master persuasive copywriting', 'content': 'Master copywriting for [PURPOSE]. Include: research, psychology, headlines, storytelling, benefits, objections, social proof, urgency, CTAs, testing, and optimization. Create copy that converts. Include copywriting templates and swipe file.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['copywriting', 'persuasion', 'conversion']},
    
    {'category_id': 'social_media', 'title': 'Social Media Empire Builder', 'description': 'Build social media business', 'content': 'Build social media business in [NICHE]. Include: account growth, content strategy, monetization streams, brand deals, products, services, community, and scaling to $50K+/month. Create social media empire. Include growth plan and monetization strategy.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['social media', 'business', 'monetization']},
    
    {'category_id': 'development_tech', 'title': 'Tech Startup Blueprint', 'description': 'Build successful tech startup', 'content': 'Build tech startup from idea to scale. Include: validation, MVP development, tech stack, team building, funding, launch, growth, scaling, and exit strategy. Create successful tech startup. Include startup roadmap and resources.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['startup', 'tech', 'scaling']},
    
    {'category_id': 'psychology', 'title': 'Behavioral Psychology System', 'description': 'Apply psychology to business', 'content': 'Apply behavioral psychology to [BUSINESS]. Include: cognitive biases, decision-making, motivation, habits, persuasion, influence, emotions, and behavior change. Use psychology to grow business. Include psychology framework and tactics.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['psychology', 'behavior', 'persuasion']},
    
    {'category_id': 'research_analysis', 'title': 'Market Research System', 'description': 'Conduct professional market research', 'content': 'Conduct market research for [BUSINESS]. Include: market size, customer segments, pain points, competition, trends, opportunities, threats, and strategic recommendations. Create comprehensive market research report. Include research templates and frameworks.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '40 min', 'tags': ['market research', 'analysis', 'insights']},
    
    # Additional Free Prompts (30)
    {'category_id': 'marketing_sales', 'title': 'Value Proposition Generator', 'description': 'Create compelling value propositions', 'content': 'Create value proposition for [PRODUCT]. Include: target customer, problem, solution, benefits.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['value proposition', 'positioning', 'marketing']},
    {'category_id': 'content_creation', 'title': 'Blog Post Outline', 'description': 'Structure blog posts', 'content': 'Create outline for [TOPIC]. Include: intro, sections, key points, conclusion.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['blog', 'outline', 'writing']},
    {'category_id': 'writing', 'title': 'Email Template Creator', 'description': 'Create email templates', 'content': 'Create email template for [PURPOSE]. Include: subject, body, CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['email', 'template', 'communication']},
    {'category_id': 'social_media', 'title': 'Content Calendar Planner', 'description': 'Plan social content', 'content': 'Create 30-day content calendar for [PLATFORM]. Include: themes, post types, timing.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '10 min', 'tags': ['calendar', 'planning', 'content']},
    {'category_id': 'freelancing', 'title': 'Service Package Creator', 'description': 'Package services effectively', 'content': 'Create service package for [SERVICE]. Include: deliverables, timeline, price.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['services', 'packages', 'pricing']},
    {'category_id': 'business_strategy', 'title': 'Competitive Analysis Framework', 'description': 'Analyze competitors', 'content': 'Analyze [COMPETITOR]. Include: products, pricing, marketing, strengths, weaknesses.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['competition', 'analysis', 'research']},
    {'category_id': 'productivity', 'title': 'Goal Setting Template', 'description': 'Set achievable goals', 'content': 'Set goals for [OBJECTIVE]. Include: specific, measurable, achievable, relevant, time-bound.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['goals', 'planning', 'achievement']},
    {'category_id': 'development_tech', 'title': 'Project Structure Generator', 'description': 'Organize code projects', 'content': 'Create project structure for [PROJECT]. Include: folders, files, naming conventions.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['project', 'structure', 'organization']},
    {'category_id': 'learning_education', 'title': 'Study Notes Template', 'description': 'Take effective notes', 'content': 'Create notes template for [SUBJECT]. Include: key concepts, examples, questions.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['notes', 'study', 'learning']},
    {'category_id': 'money_making', 'title': 'Side Hustle Planner', 'description': 'Plan side hustle', 'content': 'Plan side hustle for [IDEA]. Include: validation, setup, marketing, scaling.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['side hustle', 'planning', 'income']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Final mega batch complete!")
