from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    # Free Prompts
    {'category_id': 'marketing_sales', 'title': 'Instagram Bio Optimizer', 'description': 'Write converting Instagram bios', 'content': 'Create Instagram bio for [NICHE]. Include: value proposition, keywords, CTA, link strategy, emojis. Make it searchable and clickable.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['instagram', 'bio', 'profile']},
    {'category_id': 'content_creation', 'title': 'YouTube Thumbnail Text Ideas', 'description': 'Create clickable thumbnail text', 'content': 'Generate 15 thumbnail text ideas for [VIDEO TOPIC]. Use curiosity, numbers, power words. Keep under 6 words.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['youtube', 'thumbnails', 'ctr']},
    {'category_id': 'writing', 'title': 'Product Description Template', 'description': 'Write converting product descriptions', 'content': 'Write product description for [PRODUCT]. Include: attention-grabbing headline, key features, benefits, specifications, use cases, CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['ecommerce', 'product', 'copywriting']},
    {'category_id': 'social_media', 'title': 'Viral Hooks Generator', 'description': 'Create attention-grabbing hooks', 'content': 'Generate 20 viral hooks for [TOPIC]. Use: questions, bold statements, shocking facts, curiosity gaps, pattern interrupts.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['hooks', 'viral', 'attention']},
    {'category_id': 'freelancing', 'title': 'Project Scope Document', 'description': 'Define clear project scope', 'content': 'Create project scope for [PROJECT]. Include: objectives, deliverables, timeline, exclusions, assumptions, acceptance criteria.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['scope', 'project', 'clarity']},
    {'category_id': 'business_strategy', 'title': 'Competitor Analysis Framework', 'description': 'Analyze competitors systematically', 'content': 'Analyze [COMPETITOR] in [INDUSTRY]. Cover: products, pricing, marketing, strengths, weaknesses, opportunities.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['competition', 'analysis', 'research']},
    {'category_id': 'productivity', 'title': 'Weekly Review Template', 'description': 'Reflect and plan effectively', 'content': 'Create weekly review for [GOALS]. Include: wins, lessons, metrics, next week priorities, improvements.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '10 min', 'tags': ['review', 'reflection', 'planning']},
    {'category_id': 'development_tech', 'title': 'API Endpoint Documentation', 'description': 'Document APIs clearly', 'content': 'Document [ENDPOINT]. Include: method, URL, parameters, request body, response, errors, examples.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['api', 'documentation', 'technical']},
    {'category_id': 'learning_education', 'title': 'Flashcard Generator', 'description': 'Create effective study flashcards', 'content': 'Create flashcards for [TOPIC]. Use: question/answer format, spaced repetition, active recall, mnemonics.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['flashcards', 'study', 'memory']},
    {'category_id': 'money_making', 'title': 'Passive Income Ideas Generator', 'description': 'Find passive income opportunities', 'content': 'Generate 10 passive income ideas for [SKILLS/INTERESTS]. Include: startup cost, time investment, income potential, difficulty.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['passive income', 'ideas', 'money']},
    
    # Premium Prompts
    {'category_id': 'money_making', 'title': 'Print-On-Demand Empire Builder', 'description': 'Build profitable POD business', 'content': 'Build POD business in [NICHE] to $10K+/month. Include: niche research, design strategy (trends, tools), product selection (t-shirts, mugs, etc), supplier comparison (Printful, Printify), store setup (Shopify/Etsy), SEO optimization, paid ads strategy (Facebook, Pinterest), organic marketing, customer service, scaling tactics, and automation. Include design templates and marketing calendar.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['print on demand', 'ecommerce', 'passive income']},
    
    {'category_id': 'marketing_sales', 'title': 'Influencer Outreach & Partnership System', 'description': 'Build influencer marketing machine', 'content': 'Create influencer marketing system for [BRAND]. Include: influencer research (tools, metrics), outreach templates, negotiation tactics, content briefs, contract terms, tracking systems, payment structures, relationship management, campaign optimization, and scaling to 50+ influencers. Include influencer database template and ROI calculator.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['influencer marketing', 'partnerships', 'growth']},
    
    {'category_id': 'content_creation', 'title': 'Viral Short-Form Content System', 'description': 'Master short-form video content', 'content': 'Create viral short-form content system for [PLATFORM]. Include: hook formulas, storytelling structure, editing techniques, trending audio strategy, caption psychology, posting schedule, analytics tracking, content batching, repurposing strategy, and growth tactics. Cover TikTok, Reels, Shorts. Include 30-day content calendar.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['short form', 'viral', 'video']},
    
    {'category_id': 'freelancing', 'title': 'Productized Service Launch System', 'description': 'Package services into scalable offers', 'content': 'Launch productized service for [SERVICE]. Include: service packaging, pricing tiers, deliverables definition, process documentation, sales page copy, onboarding automation, project management workflow, quality control, team building, client communication templates, upsell strategy, and scaling to $50K+/month. Include service blueprint and SOPs.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['productized services', 'scaling', 'systems']},
    
    {'category_id': 'business_strategy', 'title': 'Strategic Partnership Development', 'description': 'Build strategic business partnerships', 'content': 'Develop strategic partnerships for [BUSINESS]. Include: partner identification, value proposition, outreach strategy, partnership structure, legal agreements, revenue sharing, co-marketing campaigns, joint ventures, affiliate programs, integration strategy, relationship management, and scaling to 50+ partners. Include partnership proposal template.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['partnerships', 'strategy', 'growth']},
    
    {'category_id': 'writing', 'title': 'Content Marketing Mastery System', 'description': 'Build content engine that drives revenue', 'content': 'Create content marketing system for [BUSINESS]. Include: content strategy, keyword research, topic clusters, content calendar, writing process, SEO optimization, distribution strategy, repurposing workflow, email integration, lead generation, conversion optimization, analytics tracking, team management, and scaling to 100+ pieces monthly. Include content templates and SOPs.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['content marketing', 'seo', 'strategy']},
    
    {'category_id': 'social_media', 'title': 'Social Media Agency Blueprint', 'description': 'Start and scale social media agency', 'content': 'Build social media agency from $0 to $50K+/month. Include: niche selection, service packages, pricing strategy, client acquisition, onboarding process, content creation workflow, team building, tools/software, client reporting, retention tactics, upselling, and scaling systems. Cover Instagram, TikTok, LinkedIn services. Include agency templates and SOPs.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['agency', 'social media', 'business']},
    
    {'category_id': 'development_tech', 'title': 'SaaS Growth & Scaling Strategy', 'description': 'Scale SaaS from $0 to $1M ARR', 'content': 'Scale [SAAS PRODUCT] to $1M+ ARR. Include: product-market fit validation, pricing optimization, onboarding flow, activation metrics, retention tactics, churn reduction, referral program, content marketing, SEO strategy, paid acquisition, sales process, customer success, feature prioritization, technical scaling, team building, and metrics tracking. Include growth model and KPI dashboard.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['saas', 'growth', 'scaling']},
    
    {'category_id': 'psychology', 'title': 'Behavioral Psychology for Business', 'description': 'Apply psychology to business growth', 'content': 'Apply behavioral psychology to [BUSINESS]. Include: cognitive biases, decision-making triggers, habit formation, motivation psychology, social proof, scarcity, reciprocity, commitment consistency, authority, liking, unity, loss aversion, anchoring, framing effects, and behavioral economics. Create psychological framework for marketing, sales, and product design.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['psychology', 'behavior', 'persuasion']},
    
    {'category_id': 'research_analysis', 'title': 'Market Research & Validation Framework', 'description': 'Validate business ideas scientifically', 'content': 'Conduct market research for [BUSINESS IDEA]. Include: market size analysis, customer interviews, surveys, competitor analysis, keyword research, trend analysis, pricing research, distribution channels, SWOT analysis, financial projections, risk assessment, and go/no-go decision framework. Include research templates and validation checklist.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '40 min', 'tags': ['market research', 'validation', 'analysis']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Batch 1 complete!")
