from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    # Free Prompts
    {'category_id': 'marketing_sales', 'title': 'Email Signature Generator', 'description': 'Professional email signatures', 'content': 'Create email signature for [ROLE]. Include: name, title, contact, social, CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['email', 'branding', 'professional']},
    {'category_id': 'content_creation', 'title': 'Video Script Outline', 'description': 'Structure engaging videos', 'content': 'Create video outline for [TOPIC]. Include: hook, problem, solution, proof, CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['video', 'script', 'structure']},
    {'category_id': 'writing', 'title': 'Press Release Writer', 'description': 'Write newsworthy press releases', 'content': 'Write press release for [NEWS]. Include: headline, summary, quotes, details, contact.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['pr', 'media', 'news']},
    {'category_id': 'social_media', 'title': 'Story Highlights Ideas', 'description': 'Organize Instagram highlights', 'content': 'Create highlight categories for [NICHE]. Include: covers, names, content types.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['instagram', 'highlights', 'organization']},
    {'category_id': 'freelancing', 'title': 'Contract Template', 'description': 'Protect your business', 'content': 'Create contract for [SERVICE]. Include: scope, payment, timeline, terms, termination.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['contract', 'legal', 'protection']},
    {'category_id': 'business_strategy', 'title': 'SWOT Analysis Template', 'description': 'Analyze business position', 'content': 'Conduct SWOT for [BUSINESS]. Include: strengths, weaknesses, opportunities, threats.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['swot', 'analysis', 'strategy']},
    {'category_id': 'productivity', 'title': 'Task Prioritization Matrix', 'description': 'Prioritize tasks effectively', 'content': 'Prioritize tasks using Eisenhower Matrix. Include: urgent/important, schedule, delegate, eliminate.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['prioritization', 'tasks', 'productivity']},
    {'category_id': 'development_tech', 'title': 'Code Comments Generator', 'description': 'Document code properly', 'content': 'Generate comments for [CODE]. Include: purpose, parameters, returns, examples.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['code', 'documentation', 'comments']},
    {'category_id': 'learning_education', 'title': 'Quiz Generator', 'description': 'Create study quizzes', 'content': 'Generate quiz for [TOPIC]. Include: multiple choice, true/false, short answer.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['quiz', 'testing', 'study']},
    {'category_id': 'money_making', 'title': 'Pricing Strategy Calculator', 'description': 'Price products correctly', 'content': 'Calculate pricing for [PRODUCT]. Include: costs, margin, value, competitors, psychology.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['pricing', 'profit', 'strategy']},
    
    # Premium Prompts
    {'category_id': 'money_making', 'title': 'E-Commerce Empire Builder', 'description': 'Build 7-figure ecommerce business', 'content': 'Build ecommerce business in [NICHE] to $1M+. Include: product selection, supplier sourcing, store setup, branding, product photography, SEO, paid ads, email marketing, conversion optimization, customer service, fulfillment, scaling, and automation. Include business plan and financial projections.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['ecommerce', 'scaling', 'business']},
    
    {'category_id': 'marketing_sales', 'title': 'Marketing Automation System', 'description': 'Automate marketing processes', 'content': 'Build marketing automation for [BUSINESS]. Include: email sequences, lead scoring, segmentation, workflows, CRM integration, analytics, personalization, retargeting, and optimization. Automate 80% of marketing tasks. Include automation blueprint and workflows.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['automation', 'marketing', 'efficiency']},
    
    {'category_id': 'content_creation', 'title': 'Content Strategy Framework', 'description': 'Build comprehensive content strategy', 'content': 'Create content strategy for [BUSINESS]. Include: goals, audience, content pillars, formats, channels, calendar, SEO, distribution, promotion, analytics, team, budget, and scaling. Build content engine that drives results. Include strategy document and calendar.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['content strategy', 'planning', 'marketing']},
    
    {'category_id': 'freelancing', 'title': 'Service Business Scaling System', 'description': 'Scale service business to 7-figures', 'content': 'Scale service business to $1M+. Include: positioning, service packaging, pricing strategy, sales system, delivery process, team building, operations, client success, retention, referrals, and automation. Create scalable service business. Include scaling roadmap and SOPs.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['service business', 'scaling', 'systems']},
    
    {'category_id': 'business_strategy', 'title': 'Business Model Innovation', 'description': 'Create innovative business models', 'content': 'Innovate business model for [INDUSTRY]. Include: value proposition, revenue streams, cost structure, key resources, partners, customer segments, channels, and competitive advantage. Create disruptive business model. Include business model canvas.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['business model', 'innovation', 'strategy']},
    
    {'category_id': 'writing', 'title': 'Content Writing Mastery System', 'description': 'Master professional content writing', 'content': 'Master content writing for [PURPOSE]. Include: research, ideation, outlining, writing, editing, SEO, formatting, publishing, promotion, and analytics. Create content that ranks and converts. Include writing templates and checklist.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['content writing', 'seo', 'mastery']},
    
    {'category_id': 'social_media', 'title': 'Social Media Management System', 'description': 'Manage social media efficiently', 'content': 'Manage social media for [BUSINESS]. Include: strategy, content creation, scheduling, engagement, analytics, reporting, team management, tools, and optimization. Manage multiple accounts efficiently. Include management system and templates.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['social media', 'management', 'efficiency']},
    
    {'category_id': 'development_tech', 'title': 'Software Development Framework', 'description': 'Build software products efficiently', 'content': 'Develop [SOFTWARE] efficiently. Include: requirements, architecture, tech stack, development process, testing, deployment, maintenance, scaling, and team management. Build quality software on time and budget. Include development roadmap.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['software', 'development', 'framework']},
    
    {'category_id': 'psychology', 'title': 'Consumer Psychology Framework', 'description': 'Understand customer psychology', 'content': 'Apply consumer psychology to [BUSINESS]. Include: buying triggers, decision-making, pain points, desires, objections, emotions, biases, and behavior patterns. Use psychology to increase conversions. Include psychology framework and tactics.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['psychology', 'consumer behavior', 'conversion']},
    
    {'category_id': 'research_analysis', 'title': 'Data Analytics Framework', 'description': 'Make data-driven decisions', 'content': 'Implement data analytics for [BUSINESS]. Include: KPIs, data collection, analysis, visualization, insights, reporting, and optimization. Use data to make better decisions and improve results. Include analytics dashboard and framework.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['analytics', 'data', 'insights']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Batch 4 complete!")
