from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    # Free Prompts
    {'category_id': 'marketing_sales', 'title': 'Landing Page Headline Generator', 'description': 'Write converting headlines', 'content': 'Generate 15 landing page headlines for [OFFER]. Use: benefit-driven, curiosity, urgency, specificity.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['landing page', 'headlines', 'conversion']},
    {'category_id': 'content_creation', 'title': 'Blog Post Ideas Generator', 'description': 'Never run out of content ideas', 'content': 'Generate 30 blog post ideas for [NICHE]. Include: how-to, listicles, case studies, comparisons, guides.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['blogging', 'ideas', 'content']},
    {'category_id': 'writing', 'title': 'Email Newsletter Template', 'description': 'Write engaging newsletters', 'content': 'Create newsletter template for [TOPIC]. Include: subject line, opening, value section, CTA, PS.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['newsletter', 'email', 'engagement']},
    {'category_id': 'social_media', 'title': 'Instagram Caption Templates', 'description': 'Write engaging captions fast', 'content': 'Create 10 caption templates for [NICHE]. Include: hooks, storytelling, value, CTA, hashtags.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['instagram', 'captions', 'templates']},
    {'category_id': 'freelancing', 'title': 'Client Onboarding Checklist', 'description': 'Streamline new client setup', 'content': 'Create onboarding checklist for [SERVICE]. Include: contract, payment, kickoff, access, timeline.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['onboarding', 'clients', 'process']},
    {'category_id': 'business_strategy', 'title': 'Business Model Canvas', 'description': 'Map your business model', 'content': 'Create business model canvas for [BUSINESS]. Cover: value proposition, customers, channels, revenue, resources, activities, partners, costs.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '15 min', 'tags': ['business model', 'strategy', 'planning']},
    {'category_id': 'productivity', 'title': 'Time Blocking Schedule', 'description': 'Plan your ideal day', 'content': 'Create time-blocked schedule for [ROLE]. Include: deep work, meetings, breaks, admin, personal time.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['time blocking', 'schedule', 'productivity']},
    {'category_id': 'development_tech', 'title': 'Bug Report Template', 'description': 'Report bugs effectively', 'content': 'Create bug report for [ISSUE]. Include: steps to reproduce, expected vs actual, environment, screenshots.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['bugs', 'testing', 'development']},
    {'category_id': 'learning_education', 'title': 'Study Plan Creator', 'description': 'Plan effective study sessions', 'content': 'Create study plan for [SUBJECT]. Include: topics, time allocation, active recall, practice tests, review.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '10 min', 'tags': ['study', 'planning', 'learning']},
    {'category_id': 'money_making', 'title': 'Side Hustle Validator', 'description': 'Validate side hustle ideas', 'content': 'Validate [SIDE HUSTLE IDEA]. Check: market demand, competition, skills needed, startup cost, time required, income potential.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['side hustle', 'validation', 'ideas']},
    
    # Premium Prompts
    {'category_id': 'money_making', 'title': 'Affiliate Marketing Authority Site', 'description': 'Build $10K+/month affiliate site', 'content': 'Build affiliate site in [NICHE] to $10K+/month. Include: niche selection, keyword research, content strategy, SEO optimization, link building, affiliate program selection, conversion optimization, email list building, traffic sources, monetization tactics, scaling strategy, and automation. Include content calendar and keyword research template.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['affiliate marketing', 'seo', 'passive income']},
    
    {'category_id': 'marketing_sales', 'title': 'Customer Journey Mapping & Optimization', 'description': 'Optimize every customer touchpoint', 'content': 'Map and optimize customer journey for [BUSINESS]. Include: awareness stage, consideration stage, decision stage, retention stage, advocacy stage, touchpoint analysis, pain points, opportunities, content strategy, conversion optimization, retention tactics, and measurement framework. Create journey map and optimization roadmap.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['customer journey', 'optimization', 'ux']},
    
    {'category_id': 'content_creation', 'title': 'Podcast Production & Monetization System', 'description': 'Launch and scale profitable podcast', 'content': 'Launch podcast in [NICHE] to $10K+/month. Include: concept development, format selection, equipment setup, recording workflow, editing process, distribution strategy, guest booking, audience growth, sponsorship acquisition, premium content, community building, repurposing strategy, and monetization streams. Include production checklist and sponsor pitch deck.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '40 min', 'tags': ['podcast', 'audio', 'monetization']},
    
    {'category_id': 'freelancing', 'title': 'Premium Service Packaging System', 'description': 'Package services for premium pricing', 'content': 'Package [SERVICE] for premium pricing ($5K-$50K). Include: positioning strategy, signature methodology, service tiers, deliverables definition, pricing justification, sales process, proposal template, contract terms, onboarding workflow, project management, and client results documentation. Include service blueprint and sales scripts.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['premium services', 'pricing', 'positioning']},
    
    {'category_id': 'business_strategy', 'title': 'Scaling Operations & Systems', 'description': 'Scale business operations efficiently', 'content': 'Scale operations for [BUSINESS] from $X to $Y revenue. Include: process documentation, team structure, hiring strategy, tools/software, automation opportunities, KPIs, quality control, customer service, financial systems, legal compliance, and scaling roadmap. Create operations manual and org chart.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['operations', 'scaling', 'systems']},
    
    {'category_id': 'writing', 'title': 'Copywriting Mastery Framework', 'description': 'Master persuasive copywriting', 'content': 'Master copywriting for [MEDIUM]. Include: research process, customer psychology, headline formulas, storytelling techniques, benefit vs features, objection handling, social proof, urgency/scarcity, CTA optimization, editing process, A/B testing, and conversion tracking. Cover sales pages, emails, ads, landing pages. Include swipe file and templates.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['copywriting', 'persuasion', 'conversion']},
    
    {'category_id': 'social_media', 'title': 'Personal Brand Monetization System', 'description': 'Turn personal brand into income', 'content': 'Monetize personal brand in [NICHE]. Include: positioning, content strategy, audience building, engagement tactics, email list growth, product creation, service offerings, sponsorships, affiliate income, speaking opportunities, consulting, and multiple revenue streams. Create monetization roadmap and content calendar.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['personal brand', 'monetization', 'influence']},
    
    {'category_id': 'development_tech', 'title': 'Mobile App Development & Launch', 'description': 'Build and launch successful mobile app', 'content': 'Develop and launch [APP IDEA]. Include: market validation, feature prioritization, tech stack selection, UI/UX design, development process, testing strategy, app store optimization, launch strategy, user acquisition, monetization, analytics, iteration process, and scaling. Include product roadmap and launch checklist.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['mobile app', 'development', 'launch']},
    
    {'category_id': 'psychology', 'title': 'Influence & Persuasion Mastery', 'description': 'Master the art of influence', 'content': 'Master influence and persuasion for [CONTEXT]. Include: Cialdini principles, social proof, authority, scarcity, reciprocity, commitment, liking, unity, framing, anchoring, loss aversion, storytelling, emotional triggers, objection handling, and ethical persuasion. Include persuasion frameworks and scripts.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['influence', 'persuasion', 'psychology']},
    
    {'category_id': 'research_analysis', 'title': 'Competitive Intelligence System', 'description': 'Monitor and analyze competitors', 'content': 'Build competitive intelligence system for [INDUSTRY]. Include: competitor identification, monitoring tools, data collection, analysis framework, SWOT analysis, strategic insights, opportunity identification, threat assessment, reporting system, and strategic response. Create competitor tracking dashboard and analysis template.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['competitive intelligence', 'analysis', 'strategy']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Batch 2 complete!")
