from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    # Free Prompts
    {'category_id': 'marketing_sales', 'title': 'Social Media Ad Copy', 'description': 'Write converting ad copy', 'content': 'Write ad copy for [PRODUCT] on [PLATFORM]. Include: hook, benefit, social proof, CTA.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['ads', 'social media', 'copywriting']},
    {'category_id': 'content_creation', 'title': 'Video Thumbnail Ideas', 'description': 'Design clickable thumbnails', 'content': 'Create 10 thumbnail concepts for [VIDEO]. Include: text, colors, emotions, faces, contrast.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '5 min', 'tags': ['thumbnails', 'design', 'ctr']},
    {'category_id': 'writing', 'title': 'About Page Writer', 'description': 'Write compelling about pages', 'content': 'Write about page for [BUSINESS]. Include: story, mission, values, team, social proof.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['about page', 'website', 'branding']},
    {'category_id': 'social_media', 'title': 'Hashtag Strategy', 'description': 'Find best hashtags', 'content': 'Create hashtag strategy for [NICHE]. Include: big, medium, small hashtags, branded tags.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['hashtags', 'reach', 'discovery']},
    {'category_id': 'freelancing', 'title': 'Project Proposal Template', 'description': 'Win more projects', 'content': 'Create proposal for [PROJECT]. Include: understanding, solution, timeline, pricing, terms.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['proposals', 'clients', 'sales']},
    {'category_id': 'business_strategy', 'title': 'Competitive Advantage Analysis', 'description': 'Find your unique edge', 'content': 'Identify competitive advantage for [BUSINESS]. Include: strengths, differentiators, value proposition.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['competitive advantage', 'strategy', 'positioning']},
    {'category_id': 'productivity', 'title': 'Daily Routine Optimizer', 'description': 'Design productive routines', 'content': 'Optimize daily routine for [GOAL]. Include: morning, work blocks, breaks, evening, sleep.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '8 min', 'tags': ['routine', 'habits', 'productivity']},
    {'category_id': 'development_tech', 'title': 'Git Workflow Setup', 'description': 'Organize code workflow', 'content': 'Setup Git workflow for [PROJECT]. Include: branches, commits, pull requests, code review.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['git', 'workflow', 'development']},
    {'category_id': 'learning_education', 'title': 'Learning Path Creator', 'description': 'Plan skill development', 'content': 'Create learning path for [SKILL]. Include: resources, milestones, practice, projects.', 'is_premium': 0, 'difficulty': 'Beginner', 'estimated_time': '10 min', 'tags': ['learning', 'skills', 'development']},
    {'category_id': 'money_making', 'title': 'Revenue Stream Ideas', 'description': 'Find new income sources', 'content': 'Generate revenue stream ideas for [BUSINESS]. Include: products, services, passive income, partnerships.', 'is_premium': 0, 'difficulty': 'Intermediate', 'estimated_time': '10 min', 'tags': ['revenue', 'income', 'monetization']},
    
    # Premium Prompts
    {'category_id': 'money_making', 'title': 'Coaching Business Blueprint', 'description': 'Build 6-figure coaching business', 'content': 'Build coaching business in [NICHE] to $100K+. Include: positioning, signature framework, pricing tiers, client acquisition, sales process, program delivery, client results, testimonials, scaling, team building, and automation. Include program outline and sales scripts.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['coaching', 'business', 'scaling']},
    
    {'category_id': 'marketing_sales', 'title': 'Sales Funnel Optimization System', 'description': 'Optimize every funnel stage', 'content': 'Optimize sales funnel for [PRODUCT]. Include: traffic analysis, landing page optimization, email sequences, conversion tracking, cart abandonment, upsells, retention, analytics, A/B testing, and scaling. Increase conversion rates 2-3x. Include optimization checklist and testing framework.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['funnel optimization', 'conversion', 'cro']},
    
    {'category_id': 'content_creation', 'title': 'Content Repurposing System', 'description': 'Maximize content ROI', 'content': 'Create content repurposing system for [CONTENT TYPE]. Include: core content creation, repurposing strategy, platform optimization, distribution schedule, automation tools, team workflow, and scaling to 50+ pieces from one source. Include repurposing matrix and workflow.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['repurposing', 'efficiency', 'content']},
    
    {'category_id': 'freelancing', 'title': 'Freelance to Agency Transition', 'description': 'Scale from solo to agency', 'content': 'Transition from freelancer to agency in [SERVICE]. Include: positioning shift, service packaging, team building, hiring process, project management, quality control, client communication, pricing strategy, operations, and scaling to $50K+/month. Include transition roadmap and SOPs.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['agency', 'scaling', 'transition']},
    
    {'category_id': 'business_strategy', 'title': 'Strategic Planning Framework', 'description': 'Create winning business strategy', 'content': 'Develop strategic plan for [BUSINESS]. Include: vision/mission, market analysis, competitive positioning, strategic objectives, key initiatives, resource allocation, KPIs, quarterly planning, execution framework, and tracking. Create strategic plan document and OKR framework.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['strategy', 'planning', 'execution']},
    
    {'category_id': 'writing', 'title': 'Content Marketing Strategy', 'description': 'Build content that converts', 'content': 'Create content marketing strategy for [BUSINESS]. Include: content pillars, keyword research, content calendar, SEO optimization, distribution channels, lead magnets, email integration, conversion optimization, analytics, and scaling to 100+ pieces monthly. Include content calendar and SEO strategy.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['content marketing', 'strategy', 'seo']},
    
    {'category_id': 'social_media', 'title': 'Social Media Growth Hacking', 'description': 'Rapid social media growth', 'content': 'Grow [PLATFORM] account to 50K+ followers in [NICHE]. Include: growth hacks, viral content, engagement tactics, collaboration strategy, automation tools, analytics, monetization, and scaling. Include growth roadmap and content templates.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['growth hacking', 'social media', 'viral']},
    
    {'category_id': 'development_tech', 'title': 'Tech Startup Launch System', 'description': 'Launch tech startup successfully', 'content': 'Launch [TECH STARTUP] from idea to market. Include: validation, MVP development, tech stack, team building, funding strategy, go-to-market, user acquisition, growth tactics, metrics tracking, and scaling. Include startup roadmap and launch checklist.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['startup', 'tech', 'launch']},
    
    {'category_id': 'psychology', 'title': 'Behavioral Design Framework', 'description': 'Design products that change behavior', 'content': 'Apply behavioral design to [PRODUCT/SERVICE]. Include: habit formation, triggers, motivation, ability, prompts, feedback loops, rewards, gamification, and behavior change frameworks. Create behavioral design blueprint.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['behavioral design', 'psychology', 'ux']},
    
    {'category_id': 'research_analysis', 'title': 'Market Research & Insights', 'description': 'Conduct professional market research', 'content': 'Conduct market research for [PRODUCT/SERVICE]. Include: market size, customer segments, pain points, buying behavior, competitive landscape, pricing analysis, distribution channels, trends, opportunities, and strategic recommendations. Include research report template.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '40 min', 'tags': ['market research', 'insights', 'analysis']},
]

init_database()
print(f"Adding {len(PROMPTS)} prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Batch 3 complete!")
