from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    {'category_id': 'money_making', 'title': 'Dropshipping 2.0 - Winning Product System', 'description': 'Find and scale winning dropshipping products', 'content': 'Build profitable dropshipping store for [NICHE]. Include: winning product criteria, product research tools (Ecomhunt, Dropship Rabbit), supplier vetting, Shopify store optimization, product page conversion tactics, upsell/cross-sell strategy, Facebook/TikTok ad creatives, influencer marketing, email flows, customer service automation, and scaling to $100K/month. Include product validation checklist and ad testing framework.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['dropshipping', 'ecommerce', 'shopify']},
    {'category_id': 'money_making', 'title': 'Consulting Business - $500/Hour Rate', 'description': 'Build premium consulting practice', 'content': 'Build consulting business in [EXPERTISE] commanding $500+/hour. Include: positioning strategy, signature methodology, client acquisition (speaking, writing, referrals), discovery call framework, proposal system, engagement models (hourly, project, retainer), scope definition, deliverable templates, client management, results documentation, case study creation, and scaling strategies. Include pricing justification and objection handling.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['consulting', 'premium pricing', 'expertise']},
    {'category_id': 'money_making', 'title': 'Licensing & Royalty Income Streams', 'description': 'Create passive income through licensing', 'content': 'Generate licensing income from [INTELLECTUAL PROPERTY]. Include: IP identification and protection, licensing agreement structure, royalty negotiation, partner identification, pitch strategy, contract terms, quality control, territory management, renewal strategies, and portfolio building. Cover patents, trademarks, designs, content, and methodologies. Include agreement templates.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['licensing', 'royalties', 'passive income']},
    {'category_id': 'marketing_sales', 'title': 'Conversion Rate Optimization Playbook', 'description': 'Double conversion rates systematically', 'content': 'Optimize [WEBSITE/FUNNEL] for maximum conversions. Include: conversion research (heatmaps, recordings, surveys), hypothesis generation, A/B testing framework, landing page optimization, checkout flow improvement, trust building elements, urgency/scarcity tactics, mobile optimization, page speed, copywriting improvements, and testing prioritization. Target 2-3x conversion improvement. Include testing roadmap and analytics setup.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['cro', 'optimization', 'conversion']},
    {'category_id': 'marketing_sales', 'title': 'Google Ads Profit Maximization', 'description': 'Scale Google Ads profitably', 'content': 'Scale Google Ads for [BUSINESS] to $50K+/month spend. Include: campaign structure (Search, Shopping, Display, YouTube), keyword research, negative keyword strategy, ad copy testing, landing page optimization, Quality Score improvement, bid strategies, audience targeting, remarketing, conversion tracking, attribution modeling, and ROAS optimization. Include account audit checklist and scaling framework.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['google ads', 'ppc', 'paid traffic']},
    {'category_id': 'marketing_sales', 'title': 'Joint Venture Partnership System', 'description': 'Leverage other audiences for growth', 'content': 'Build JV partnership strategy for [BUSINESS]. Include: partner identification, outreach strategy, win-win offer creation, affiliate program design, co-marketing campaigns, webinar partnerships, bundle deals, commission structures, tracking systems, relationship management, and scaling to 50+ partners. Include partnership proposal template and agreement terms.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['partnerships', 'jv', 'growth']},
    {'category_id': 'freelancing', 'title': 'Done-For-You Service Productization', 'description': 'Package services for scalability', 'content': 'Productize [SERVICE] into scalable offering. Include: service scope definition, deliverable standardization, process documentation, pricing tiers, timeline commitments, quality standards, team training, client onboarding automation, project management system, and delivery workflow. Transform custom work into repeatable system. Include SOPs and templates.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['productization', 'services', 'scalability']},
    {'category_id': 'freelancing', 'title': 'International Client Acquisition', 'description': 'Land high-paying international clients', 'content': 'Acquire clients from [TARGET COUNTRIES] for [SERVICE]. Include: market research, cultural considerations, timezone management, payment processing, contract considerations, communication strategies, portfolio localization, platform selection, pricing strategy, and trust building. Focus on high-value markets (US, UK, Australia, Canada). Include outreach templates.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['international', 'clients', 'global']},
    {'category_id': 'business_strategy', 'title': 'Exit Strategy & Business Valuation', 'description': 'Prepare business for profitable exit', 'content': 'Prepare [BUSINESS] for exit/acquisition. Include: valuation methodology (multiples, DCF), value drivers optimization, financial cleanup, documentation organization, buyer identification, business broker selection, due diligence preparation, negotiation strategy, deal structure, earnouts, and transition planning. Maximize valuation and ensure smooth exit. Include valuation calculator.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['exit strategy', 'valuation', 'acquisition']},
    {'category_id': 'business_strategy', 'title': 'Strategic Planning & Execution System', 'description': 'Create and execute winning strategy', 'content': 'Develop strategic plan for [COMPANY]. Include: vision/mission definition, SWOT analysis, competitive positioning, strategic objectives, initiative prioritization, resource allocation, KPI framework, quarterly planning, execution rhythm, accountability system, and progress tracking. Apply frameworks: Hoshin Kanri, Balanced Scorecard, OKRs. Include planning templates and dashboards.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['strategy', 'planning', 'execution']},
    {'category_id': 'content_creation', 'title': 'Authority Book Writing System', 'description': 'Write book that builds your brand', 'content': 'Write authority-building book in [NICHE]. Include: book positioning, outline development, writing process, research methodology, storytelling integration, case study inclusion, editing workflow, cover design, formatting, publishing options (traditional vs self), launch strategy, and business integration. Transform expertise into published authority. Include writing schedule and chapter templates.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['book writing', 'authority', 'publishing']},
    {'category_id': 'content_creation', 'title': 'Masterclass Course Creation', 'description': 'Create premium online course', 'content': 'Create masterclass course for [TOPIC] priced at $500-$2000. Include: curriculum design, learning outcomes, module structure, video production, slide design, workbook creation, community integration, certification program, student success system, pricing strategy, launch plan, and evergreen automation. Include course outline and production checklist.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['course creation', 'education', 'premium']},
    {'category_id': 'writing', 'title': 'Direct Response Copywriting Mastery', 'description': 'Master high-converting copy', 'content': 'Master direct response copywriting for [MEDIUM]. Include: research process, avatar deep-dive, headline formulas, lead writing, bullet crafting, storytelling, objection handling, guarantee creation, CTA optimization, and testing methodology. Study legends: Gary Halbert, John Carlton, Clayton Makepeace. Include swipe file analysis and practice exercises.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['copywriting', 'direct response', 'conversion']},
    {'category_id': 'writing', 'title': 'Content Marketing Strategy & Execution', 'description': 'Build content engine that drives revenue', 'content': 'Build content marketing system for [BUSINESS]. Include: content strategy, pillar content creation, distribution plan, SEO integration, lead magnet strategy, email capture, nurture sequences, content repurposing, team management, editorial calendar, analytics tracking, and ROI measurement. Create content that attracts, converts, and retains customers. Include 90-day plan.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['content marketing', 'strategy', 'revenue']},
    {'category_id': 'social_media', 'title': 'Twitter Growth & Monetization System', 'description': 'Build profitable Twitter presence', 'content': 'Grow Twitter to 50K+ followers and monetize in [NICHE]. Include: profile optimization, content strategy, thread writing, engagement tactics, DM strategy, Twitter Spaces, newsletter integration, product promotion, sponsorships, and community building. Include viral tweet formulas and 30-day growth plan.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['twitter', 'growth', 'monetization']},
    {'category_id': 'social_media', 'title': 'Influencer Marketing Campaign', 'description': 'Execute profitable influencer campaigns', 'content': 'Run influencer marketing campaign for [PRODUCT]. Include: influencer identification, outreach strategy, negotiation tactics, campaign brief, content guidelines, tracking/attribution, contract terms, relationship management, performance analysis, and scaling. Target ROI of 3-5x. Include influencer database and campaign templates.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['influencer marketing', 'campaigns', 'roi']},
    {'category_id': 'development_tech', 'title': 'Chrome Extension Monetization', 'description': 'Build and monetize browser extensions', 'content': 'Build profitable Chrome extension for [USE CASE]. Include: idea validation, development roadmap, user experience design, monetization strategy (freemium, subscription, ads), Chrome Web Store optimization, user acquisition, review generation, update strategy, and scaling. Include technical requirements and revenue projections.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['chrome extension', 'development', 'monetization']},
    {'category_id': 'development_tech', 'title': 'WordPress Plugin Business Model', 'description': 'Create profitable WordPress plugins', 'content': 'Build WordPress plugin business for [FUNCTIONALITY]. Include: market research, plugin development, freemium strategy, pricing tiers, WordPress.org listing optimization, support system, update management, marketing strategy, affiliate program, and scaling to $10K+ MRR. Include development roadmap and marketing plan.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['wordpress', 'plugin', 'saas']},
    {'category_id': 'learning_education', 'title': 'Expert Positioning & Thought Leadership', 'description': 'Become recognized industry expert', 'content': 'Position yourself as expert in [FIELD]. Include: expertise audit, niche selection, signature framework development, content strategy, speaking opportunities, media appearances, book writing, course creation, certification program, community building, and monetization. Transform from practitioner to recognized authority in 12-18 months.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['expertise', 'authority', 'positioning']},
    {'category_id': 'fitness_health', 'title': 'Online Fitness Coaching Business', 'description': 'Build 6-figure fitness coaching practice', 'content': 'Build online fitness coaching business in [NICHE]. Include: program design, client acquisition, assessment process, app/platform selection, nutrition planning, progress tracking, accountability systems, community building, pricing tiers, client results documentation, and scaling to $20K+ monthly. Include client onboarding and program templates.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['fitness coaching', 'online business', 'health']},
]

init_database()
print(f"Adding {len(PROMPTS)} premium prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Premium batch 3 complete!")
