from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    {'category_id': 'money_making', 'title': 'Amazon FBA Private Label Empire', 'description': 'Build 6-figure Amazon business', 'content': 'Launch profitable Amazon FBA business in [CATEGORY]. Include: product research methodology (Jungle Scout, Helium 10), supplier sourcing (Alibaba negotiation tactics), product differentiation strategy, listing optimization (A+ content, backend keywords), PPC campaign structure (auto, manual, sponsored brands), inventory management, cash flow planning, review generation system, brand registry, trademark filing, external traffic strategies, international expansion, exit strategy, and path to $50K/month. Include financial projections and risk mitigation.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['amazon fba', 'ecommerce', 'physical products']},
    {'category_id': 'money_making', 'title': 'Subscription Box Business Model', 'description': 'Launch recurring revenue subscription business', 'content': 'Build subscription box business for [NICHE]. Include: product curation strategy, supplier relationships, packaging design, pricing model (cost analysis + margins), customer acquisition strategy, retention tactics (reduce churn), unboxing experience design, referral program, upsell opportunities, fulfillment logistics, inventory management, seasonal variations, community building, and scaling to 1000+ subscribers. Include unit economics and LTV calculations.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['subscription', 'recurring revenue', 'ecommerce']},
    {'category_id': 'money_making', 'title': 'Real Estate Wholesaling System', 'description': 'Flip contracts without buying properties', 'content': 'Build real estate wholesaling business in [MARKET]. Include: motivated seller finding (direct mail, cold calling, SEO), deal analysis (ARV, repair costs, assignment fee), contract negotiation, buyer list building, disposition strategy, CRM setup, marketing budget allocation, team building (VAs, acquisition managers), legal compliance, scaling systems, and path to $10K+ per deal. Include scripts, templates, and deal calculator.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['real estate', 'wholesaling', 'investing']},
    {'category_id': 'marketing_sales', 'title': 'Webinar Funnel That Converts at 20%+', 'description': 'Build high-converting automated webinar', 'content': 'Create automated webinar funnel for [OFFER]. Include: registration page optimization, reminder sequence (email + SMS), webinar script (perfect webinar formula), slide design principles, engagement tactics (polls, Q&A), pitch sequence, stack reveal, price anchoring, scarcity mechanics, replay strategy, follow-up sequence, live vs automated strategy, and conversion optimization. Target 20%+ conversion rate. Include complete 60-90 minute script.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['webinar', 'funnel', 'conversion']},
    {'category_id': 'marketing_sales', 'title': 'Facebook Ads Mastery - $1M+ Spend Strategy', 'description': 'Scale Facebook ads profitably', 'content': 'Scale Facebook ads for [BUSINESS] from $100/day to $10K+/day. Include: campaign structure (TOF/MOF/BOF), creative testing framework, audience research, lookalike strategy, retargeting sequences, ad copy formulas, creative hooks, scaling methodology, budget allocation, bid strategies, pixel optimization, iOS14+ workarounds, attribution modeling, ROAS optimization, and agency-level reporting. Include ad examples and testing protocols.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['facebook ads', 'paid traffic', 'scaling']},
    {'category_id': 'marketing_sales', 'title': 'SEO Authority Site Blueprint', 'description': 'Build organic traffic empire', 'content': 'Build authority site generating 100K+ monthly visitors in [NICHE]. Include: keyword research strategy, content cluster methodology, topical authority building, link building tactics (white hat), on-page SEO optimization, technical SEO checklist, content production system, writer management, monetization strategy (ads, affiliate, products), traffic leak strategies, and 12-month content calendar. Include keyword research and competitor analysis.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['seo', 'content', 'organic traffic']},
    {'category_id': 'freelancing', 'title': 'Agency Model - From Freelancer to 7-Figures', 'description': 'Scale freelancing into full agency', 'content': 'Transform freelance business into 7-figure agency in [SERVICE]. Include: positioning shift, service productization, hiring roadmap (when + who), operations manual, client acquisition at scale, project management systems, quality control, team training, profit margins optimization, client retention, strategic partnerships, and growth milestones. Cover transition from doer to CEO. Include financial modeling and org chart.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['agency', 'scaling', 'business growth']},
    {'category_id': 'freelancing', 'title': 'Retainer Client Acquisition System', 'description': 'Fill your calendar with monthly retainers', 'content': 'Build retainer-based freelance business in [NICHE]. Include: retainer packaging (tiers + deliverables), pricing strategy, client qualification, outreach system, proposal template, contract terms, scope management, client onboarding, monthly reporting, retention tactics, upsell strategy, and path to $20K+ MRR. Include scripts for converting project clients to retainers and handling objections.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['retainers', 'recurring revenue', 'freelancing']},
    {'category_id': 'business_strategy', 'title': 'Acquisition Entrepreneurship Playbook', 'description': 'Buy and grow existing businesses', 'content': 'Acquire and scale existing business in [INDUSTRY]. Include: deal sourcing (brokers, direct outreach), business valuation, due diligence checklist, SBA loan process, seller financing negotiation, transition planning, quick wins identification, growth strategy, team retention, systems optimization, and exit planning. Cover buying businesses for $100K-$5M with minimal cash down. Include LOI template and valuation models.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['acquisition', 'buying business', 'entrepreneurship']},
    {'category_id': 'business_strategy', 'title': 'Franchise Development System', 'description': 'Franchise your business model', 'content': 'Franchise [BUSINESS] for rapid expansion. Include: franchisability assessment, FDD (Franchise Disclosure Document) creation, operations manual development, training program design, franchise marketing, franchisee selection criteria, support systems, royalty structure, territory planning, legal compliance, quality control, and growth projections. Transform business into scalable franchise system.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['franchise', 'expansion', 'business model']},
    {'category_id': 'content_creation', 'title': 'Netflix-Style Documentary Production', 'description': 'Produce professional documentary content', 'content': 'Produce documentary about [TOPIC]. Include: story arc development, interview techniques, B-roll planning, cinematography principles, audio recording, editing workflow, color grading, music licensing, narrative structure, character development, pacing, distribution strategy (streaming platforms, film festivals), marketing campaign, and monetization. Create production timeline and budget breakdown.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['documentary', 'video production', 'storytelling']},
    {'category_id': 'content_creation', 'title': 'Podcast to Profit System', 'description': 'Monetize podcast beyond sponsorships', 'content': 'Monetize podcast in [NICHE] with multiple revenue streams. Include: content strategy, guest booking system, production workflow, distribution optimization, audience growth tactics, sponsorship acquisition, dynamic ad insertion, premium membership tier, course/product creation, live events, community building, repurposing strategy, and path to $10K+/month. Include pitch deck for sponsors and monetization timeline.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['podcast', 'monetization', 'audio content']},
    {'category_id': 'writing', 'title': 'Ghostwriting Business - $10K+ Per Project', 'description': 'Build premium ghostwriting practice', 'content': 'Build ghostwriting business commanding $10K-$50K per project. Include: niche selection, client acquisition (CEOs, executives, experts), proposal system, interviewing methodology, writing process, project management, pricing strategy, contract templates, client management, portfolio building without attribution, referral system, and scaling with team. Cover books, articles, speeches, and thought leadership content.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['ghostwriting', 'writing business', 'premium services']},
    {'category_id': 'writing', 'title': 'Bestselling Book Launch Strategy', 'description': 'Launch book to bestseller status', 'content': 'Launch [BOOK] to bestseller lists (Amazon, NYT, WSJ). Include: pre-launch strategy (12 weeks out), advance reader team, launch team building, media outreach, podcast tour, bulk sales strategy, Amazon algorithm optimization, category selection, pricing strategy, launch week tactics, post-launch momentum, book funnel integration, and long-term marketing. Include timeline and promotional calendar.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['book launch', 'bestseller', 'publishing']},
    {'category_id': 'social_media', 'title': 'TikTok Monetization Masterclass', 'description': 'Build profitable TikTok business', 'content': 'Monetize TikTok account in [NICHE] to $10K+/month. Include: viral content formula, algorithm understanding, posting strategy, trend jacking, sound selection, hook formulas, editing techniques, Creator Fund optimization, brand deals acquisition, TikTok Shop setup, affiliate marketing, funnel integration, cross-platform strategy, and audience building to 100K+ followers. Include 30-day viral content plan.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['tiktok', 'monetization', 'viral content']},
    {'category_id': 'social_media', 'title': 'LinkedIn Lead Generation Engine', 'description': 'Generate B2B leads on autopilot', 'content': 'Build LinkedIn lead generation system for [B2B SERVICE]. Include: profile optimization, content strategy (thought leadership), connection strategy, outreach sequences, conversation framework, Sales Navigator tactics, automation tools (safely), engagement strategy, group participation, publishing articles, video content, and conversion to sales calls. Target 20-50 qualified leads monthly. Include templates and scripts.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['linkedin', 'b2b', 'lead generation']},
    {'category_id': 'development_tech', 'title': 'No-Code SaaS Builder Blueprint', 'description': 'Build SaaS without coding', 'content': 'Build [SAAS PRODUCT] using no-code tools. Include: tool selection (Bubble, Webflow, Airtable, Zapier), database design, user authentication, payment integration, email automation, UI/UX design, workflow automation, API integrations, testing protocols, launch strategy, and scaling considerations. Create functional MVP in 30 days. Include tool comparisons and cost breakdown.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['no-code', 'saas', 'mvp']},
    {'category_id': 'development_tech', 'title': 'Mobile App Monetization Strategy', 'description': 'Maximize app revenue streams', 'content': 'Monetize [MOBILE APP] with optimal strategy. Include: monetization model selection (freemium, subscription, ads, in-app purchases), pricing psychology, paywall design, ad placement optimization, subscription tier structure, retention tactics, ASO (App Store Optimization), user acquisition, LTV optimization, analytics setup, A/B testing framework, and revenue forecasting. Target $50K+ monthly revenue.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['mobile app', 'monetization', 'revenue']},
    {'category_id': 'productivity', 'title': 'Second Brain System - PKM Mastery', 'description': 'Build personal knowledge management system', 'content': 'Build Second Brain system for [PROFESSION] using [TOOL]. Include: capture system, organization methodology (PARA, Zettelkasten), progressive summarization, project workflow, creative output system, review process, digital garden, knowledge synthesis, idea generation, and productivity integration. Transform information consumption into creative output. Include templates and workflows.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['pkm', 'second brain', 'knowledge management']},
    {'category_id': 'psychology', 'title': 'Negotiation Mastery Framework', 'description': 'Win negotiations systematically', 'content': 'Master negotiation for [CONTEXT]. Include: preparation framework, BATNA development, anchoring tactics, framing techniques, emotional intelligence application, objection handling, concession strategy, closing techniques, difficult personality types, cross-cultural considerations, and practice scenarios. Apply principles from: Chris Voss, Roger Fisher, William Ury. Include scripts and role-play exercises.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['negotiation', 'persuasion', 'communication']},
]

init_database()
print(f"Adding {len(PROMPTS)} premium prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Premium batch 2 complete!")
