from add_prompts import add_prompts_batch
from db_manager import export_to_json, init_database

PROMPTS = [
    {'category_id': 'money_making', 'title': '7-Figure Info Product Empire Blueprint', 'description': 'Complete system to build million-dollar info business', 'content': 'Design a complete 7-figure info product business for [NICHE]. Include: product ladder (lead magnet → tripwire → core offer → high-ticket), pricing psychology, launch sequences, evergreen funnel automation, email nurture sequences, upsell/downsell flows, affiliate program structure, customer ascension model, lifetime value optimization, traffic sources (paid + organic), conversion rate benchmarks, team structure, tech stack, financial projections, and scaling roadmap from $0 to $1M+.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '30 min', 'tags': ['info products', 'scaling', 'business model']},
    {'category_id': 'money_making', 'title': 'AI-Powered SaaS Validation Framework', 'description': 'Validate SaaS ideas before building', 'content': 'Validate [SAAS IDEA] using comprehensive framework. Include: problem-solution fit analysis, market size calculation (TAM/SAM/SOM), competitor deep-dive (features, pricing, positioning), customer interview script (20+ questions), landing page copy + design wireframe, pricing tier strategy, unit economics modeling (CAC, LTV, churn), go-to-market strategy, MVP feature prioritization (MoSCoW method), technical feasibility assessment, 90-day launch plan, success metrics, and pivot triggers.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['saas', 'validation', 'startup']},
    {'category_id': 'money_making', 'title': 'High-Ticket Coaching Program Designer', 'description': 'Create premium coaching offers that sell', 'content': 'Design a high-ticket coaching program for [TRANSFORMATION] priced at $5K-$50K. Include: signature framework (proprietary methodology), curriculum structure (modules, milestones, deliverables), onboarding process, weekly/monthly touchpoints, accountability systems, bonus resources, community access, implementation support, results guarantee framework, application funnel, sales call script (objection handling), payment plans, client success roadmap, testimonial generation system, and program delivery platform recommendations.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '30 min', 'tags': ['coaching', 'high-ticket', 'premium']},
    {'category_id': 'marketing_sales', 'title': 'VSL (Video Sales Letter) Script Master', 'description': 'Write converting video sales letters', 'content': 'Write a complete VSL script for [PRODUCT] targeting [AVATAR]. Include: pattern interrupt hook (first 5 seconds), story-based opening, problem agitation (emotional triggers), unique mechanism reveal, origin story, social proof integration points, stack and reveal, price anchoring sequence, guarantee framework, scarcity/urgency elements, FAQ preemption, multiple CTAs, exit-intent offer, script timing markers, visual cue suggestions, music/sound recommendations, and A/B test variations for key sections. Target length: 15-25 minutes.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['vsl', 'sales', 'conversion']},
    {'category_id': 'marketing_sales', 'title': 'Product Launch Formula - Complete Campaign', 'description': 'Execute million-dollar product launches', 'content': 'Create a complete product launch campaign for [PRODUCT] using Jeff Walker\'s PLF framework. Include: pre-launch (seed launch, sideways sales letter), launch sequence (3-4 videos with content + pitch), email sequence (40+ emails across 3 weeks), social media content calendar, JV/affiliate recruitment strategy, launch math (list size, conversion rates, revenue projections), scarcity mechanics, cart open/close strategy, live event/webinar integration, post-launch survey, and evergreen conversion plan.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['launch', 'plf', 'campaign']},
    {'category_id': 'marketing_sales', 'title': 'Funnel Hacking & Reverse Engineering System', 'description': 'Decode and replicate successful funnels', 'content': 'Reverse engineer [COMPETITOR FUNNEL] and create improved version. Analyze: traffic sources (paid ads, SEO, partnerships), lead magnet strategy, opt-in page psychology, email sequence breakdown (subject lines, hooks, CTAs), tripwire offer positioning, core offer presentation, upsell/downsell flow, cart abandonment sequence, tech stack identification, conversion optimization tactics, pricing strategy, guarantee structure, and create your superior funnel blueprint with improvements.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['funnels', 'analysis', 'optimization']},
    {'category_id': 'freelancing', 'title': 'Six-Figure Freelance Business System', 'description': 'Scale freelancing to $100K+ annually', 'content': 'Build a six-figure freelance business in [NICHE]. Include: positioning strategy (specialist vs generalist), premium service packaging, value-based pricing model, client acquisition system (outbound + inbound), proposal template that closes 60%+, project management workflow, client communication framework, productized service offerings, retainer model design, team building roadmap (when to hire), financial management (taxes, retirement, insurance), time management system, and scaling from solopreneur to agency.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '35 min', 'tags': ['freelancing', 'scaling', 'six-figure']},
    {'category_id': 'freelancing', 'title': 'Premium Service Positioning & Packaging', 'description': 'Command premium rates with strategic positioning', 'content': 'Reposition [SERVICE] to command 3-5x higher rates. Include: niche-down strategy, unique selling proposition development, signature process/framework creation, case study development, authority building plan (content, speaking, media), premium brand identity, website messaging overhaul, service tier structure (good/better/best), done-for-you vs done-with-you models, results-based guarantees, client qualification criteria, and premium client attraction strategy.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['positioning', 'premium', 'branding']},
    {'category_id': 'business_strategy', 'title': 'Lean Startup Validation Playbook', 'description': 'Validate business ideas with minimal investment', 'content': 'Validate [BUSINESS IDEA] using lean startup methodology. Include: assumption mapping, riskiest assumption identification, MVP definition (smallest testable product), smoke test landing page, pre-sale campaign strategy, customer development interviews (script + analysis), build-measure-learn cycles, pivot vs persevere criteria, traction metrics, validation checklist, budget allocation ($500-$5000), timeline (30-90 days), and decision framework for next steps.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['validation', 'lean startup', 'mvp']},
    {'category_id': 'business_strategy', 'title': 'Blue Ocean Strategy Implementation', 'description': 'Create uncontested market space', 'content': 'Apply Blue Ocean Strategy to [INDUSTRY/BUSINESS]. Include: strategy canvas creation, four actions framework (eliminate-reduce-raise-create), value innovation analysis, non-customer analysis (three tiers), strategic pricing, business model reconstruction, execution roadmap, organizational alignment, tipping point leadership, and fair process implementation. Identify untapped market space and create differentiation that makes competition irrelevant.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['strategy', 'differentiation', 'innovation']},
    {'category_id': 'content_creation', 'title': 'YouTube Channel Monetization Blueprint', 'description': 'Build profitable YouTube business', 'content': 'Create a monetization strategy for YouTube channel in [NICHE]. Include: content pillars (hero/hub/hygiene), viral video formula, thumbnail psychology, title optimization, SEO strategy, upload schedule, audience retention tactics, multiple revenue streams (AdSense, sponsorships, affiliate, products, memberships), sponsor pitch template, media kit, analytics interpretation, growth hacking tactics, and path to $10K/month. Include 90-day content calendar.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['youtube', 'monetization', 'content']},
    {'category_id': 'content_creation', 'title': 'Viral Content Engineering System', 'description': 'Create content that spreads organically', 'content': 'Engineer viral content for [PLATFORM] in [NICHE]. Include: psychological triggers (emotion, identity, practical value, social currency, stories, triggers), hook formulas (pattern interrupts), content structure for maximum retention, shareability optimization, algorithm understanding, timing strategy, engagement bait tactics, comment section management, collaboration strategies, paid amplification tactics, and viral loop creation. Analyze 10 viral posts in your niche and extract patterns.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['viral', 'content', 'growth']},
    {'category_id': 'writing', 'title': 'Long-Form Sales Letter Masterclass', 'description': 'Write sales letters that print money', 'content': 'Write a long-form sales letter for [PRODUCT] using classic direct response principles. Include: headline formulas (curiosity + benefit), lead variations (story, problem, offer, prediction), fascinations, bullet writing, testimonial integration, risk reversal, guarantee crafting, price justification, order form psychology, PS strategy, and complete 5000+ word sales letter. Study: Gary Halbert, Dan Kennedy, Eugene Schwartz principles. Include A/B test variations.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '45 min', 'tags': ['copywriting', 'sales letter', 'direct response']},
    {'category_id': 'writing', 'title': 'Email Sequence Psychology & Automation', 'description': 'Build email sequences that convert on autopilot', 'content': 'Create a complete email automation system for [BUSINESS]. Include: welcome sequence (5-7 emails), indoctrination series, soap opera sequence, daily broadcast strategy, segmentation logic, behavioral triggers, re-engagement campaigns, cart abandonment sequence, post-purchase sequence, referral request sequence, win-back campaign, and sunset sequence. Write 30+ email templates with subject lines, preview text, and conversion optimization tactics.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['email marketing', 'automation', 'sequences']},
    {'category_id': 'social_media', 'title': 'Instagram Growth to 100K Blueprint', 'description': 'Systematic Instagram growth strategy', 'content': 'Grow Instagram account from 0 to 100K in [NICHE]. Include: account optimization, content pillars, posting strategy (reels/posts/stories ratio), viral reel formula, caption framework, hashtag strategy (tiered approach), engagement tactics (DM strategy, comment pods), collaboration strategy, Instagram SEO, algorithm understanding, monetization integration, analytics tracking, growth milestones, and automation tools. Include 90-day content calendar and growth projections.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['instagram', 'growth', 'social media']},
    {'category_id': 'social_media', 'title': 'Personal Brand Authority System', 'description': 'Build influential personal brand online', 'content': 'Build a personal brand in [NICHE] that attracts opportunities. Include: brand positioning statement, content strategy across platforms, thought leadership plan, signature framework/methodology, content repurposing system, engagement strategy, network building tactics, media appearances roadmap, speaking opportunities, book/course creation, monetization strategy, and authority building timeline. Transform from unknown to recognized expert in 12 months.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '35 min', 'tags': ['personal brand', 'authority', 'influence']},
    {'category_id': 'development_tech', 'title': 'SaaS Architecture & Tech Stack Blueprint', 'description': 'Design scalable SaaS infrastructure', 'content': 'Design complete tech architecture for [SAAS PRODUCT]. Include: frontend framework selection, backend architecture (monolith vs microservices), database design (SQL vs NoSQL), authentication system, API design, payment integration, email service, file storage, CDN strategy, hosting solution, CI/CD pipeline, monitoring/logging, security implementation, scalability considerations, cost optimization, and tech stack justification. Include architecture diagrams and implementation roadmap.', 'is_premium': 1, 'difficulty': 'Expert', 'estimated_time': '40 min', 'tags': ['saas', 'architecture', 'tech stack']},
    {'category_id': 'development_tech', 'title': 'API Monetization Strategy', 'description': 'Turn your API into revenue stream', 'content': 'Monetize [API] with strategic pricing and packaging. Include: pricing model selection (usage-based, tiered, freemium), rate limiting strategy, authentication methods, documentation excellence, developer onboarding, SDK creation, API marketplace listing, partnership strategy, usage analytics, billing system, support tiers, SLA definitions, and growth tactics. Include pricing calculator and revenue projections.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['api', 'monetization', 'pricing']},
    {'category_id': 'productivity', 'title': 'CEO Time Management System', 'description': 'Manage time like top executives', 'content': 'Implement CEO-level time management for [ROLE]. Include: time audit process, energy management, ideal week design, time blocking system, meeting protocols, decision-making framework, delegation matrix, focus time protection, email/communication batching, strategic thinking time, quarterly planning, weekly review system, daily routines, productivity metrics, and elimination strategies. Optimize for high-leverage activities and 10x results.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['time management', 'productivity', 'executive']},
    {'category_id': 'learning_education', 'title': 'Accelerated Learning System', 'description': 'Master any skill 10x faster', 'content': 'Create accelerated learning plan for [SKILL]. Include: skill deconstruction, 80/20 analysis, learning roadmap, deliberate practice design, feedback loops, spaced repetition system, interleaving strategy, mental models, memory techniques, teaching-to-learn approach, project-based learning, mentor finding strategy, learning metrics, and 90-day mastery plan. Apply principles from: Josh Waitzkin, Tim Ferriss, Scott Young.', 'is_premium': 1, 'difficulty': 'Advanced', 'estimated_time': '30 min', 'tags': ['learning', 'skill acquisition', 'mastery']},
]

init_database()
print(f"Adding {len(PROMPTS)} premium prompts...")
add_prompts_batch(PROMPTS)
export_to_json()
print("✅ Premium batch 1 complete!")
